<?php

use Flywheel\Document\Html;
$document = $this->document();
/** @var Html $document */
$document->addJs('assets/plugins/jquery/jquery-1.11.1.min.js');
$document->addJs('assets/plugins/notify.min.js');
$document->addJs('assets/plugins/jquery-autonumeric/autoNumeric.js');
$document->addJs('assets/plugins/bootstrap-tag/bootstrap-tagsinput.min.js');
$document->addCss('assets/plugins/bootstrap-tag/bootstrap-tagsinput.css');
$document->addJs('assets/js/jquery.slimscroll.min.js');
/*$document->addJs('assets/ckeditor/ckeditor.js');*/
$title = 'Danh sách bài viết';

?>
<script src="//cdn.ckeditor.com/4.5.9/standard/ckeditor.js"></script>
<div class="container-fluid container-fixed-lg">
    <table class="table table-bordered">
        <tr>
            <td>
                Tiêu đề bài viết
            </td>
            <td>
                <input value="" placeholder="Nhập tiêu đề bài viết" name="title" id="_title" class="form-control" />
            </td>
        </tr>
        <tr>
            <td>Tóm tắt nội dung</td>
            <td>
            <textarea  class="form-control" rows="5" id="comment">

            </textarea>
            </td>
        </tr>
        <tr>
            <td>
                Nội dung
            </td>
            <td>
            <textarea id="content" name="content" class="content">

            </textarea>
                <script  type="text/javascript">
                    CKEDITOR.replace( 'content' );
                </script>
            </td>
        </tr>
    </table>

</div>


