<?php

use Flywheel\Document\Html;
$document = $this->document();
/** @var Html $document */

$document->addJs('assets/plugins/jquery/jquery-1.11.1.min.js');
$title = 'Danh sách bài viết';

?>
<script src="//cdn.ckeditor.com/4.5.9/standard/ckeditor.js"></script>
<div class="container-fluid container-fixed-lg">
    <table class="table table-bordered">
        <tr>
            <td>
                Tiêu đề bài viết
            </td>
            <td>
                <input value="" placeholder="Nhập tiêu đề bài viết" name="title" id="_title" class="form-control" />
            </td>
        </tr>
        <tr>
            <td>Tóm tắt nội dung</td>
            <td>
            <textarea  class="form-control" rows="5" name="summary" id="comment">

            </textarea>
            </td>
        </tr>
        <tr>
            <td>
                Nội dung
            </td>
            <td>
            <textarea id="content" name="content" class="content">

            </textarea>
                <script  type="text/javascript">
                    CKEDITOR.replace( 'content' );
                </script>
            </td>
        </tr>
        <tr>
            <td>
                Tác giả
            </td>
            <td>
                <select class="form-control" name="author">
                    <?php foreach ($customer as $item_customer){?>
                        <?php /** @var \Customer $item_customer */ ?>
                            <option value="<?=$item_customer->getId() ?>"><?= $item_customer->getUsername() ?></option>
                    <?php }?>
                </select>
            </td>
        </tr>
        <tr>
            <td>
                Danh mục bài viết
            </td>
            <td>
                <select class="form-control">
                        <optgroup label="Tin tức">
                            <option value="volvo">Tiếng Việt</option>
                            <option value="saab">Tiếng Trung</option>
                        </optgroup>
                        <optgroup label="Học Tiếng Việt">
                            <option value="mercedes">Học tiếng việt</option>
                        </optgroup>
                        <optgroup label="Học Tiếng Trung">
                            <option value="mercedes">Khóa học cơ bản</option>
                            <option>Ôn thi</option>
                        </optgroup>
                        <optgroup label="Blogger">
                            <option value="mercedes">Blogger</option>
                        </optgroup>
                </select>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit">Thêm mới</button>
            </td>
        </tr>
    </table>

</div>


