<?php

use Flywheel\Document\Html;
$document = $this->document();
/** @var Html $document */

$document->addJs('assets/plugins/jquery/jquery-1.11.1.min.js');
$document->addJs('assets/ckeditor/ckeditor.js','TOP');
$title = 'Danh sách bài viết';

?>
<!--<script src="//cdn.ckeditor.com/4.5.9/standard/ckeditor.js"></script>-->
<form method="post">
<div class="container-fluid container-fixed-lg">
    <table class="table table-bordered">
        <tr>
            <td>
                Tiêu đề bài viết
            </td>
            <td>
                <input value="" placeholder="Nhập tiêu đề bài viết" name="title" id="_title" class="form-control" />
            </td>
        </tr>
        <tr>
            <td>Tóm tắt nội dung</td>
            <td>
            <textarea  class="form-control" rows="5" name="summary" id="comment">

            </textarea>
            </td>
        </tr>
        <tr>
            <td>
                Nội dung
            </td>
            <td>
            <textarea id="content" name="content" class="content">

            </textarea>
                <script>
                    CKEDITOR.replace( 'content' );
                   
                </script>
            </td>
        </tr>
        <tr>
            <td>
                Tác giả
            </td>
            <td>
                <select class="form-control" name="author">
                    <?php foreach ($customer as $item_customer){?>
                        <?php /** @var \Customer $item_customer */ ?>
                            <option value="<?=$item_customer->getId() ?>"><?= $item_customer->getUsername() ?></option>
                    <?php }?>
                </select>
            </td>
        </tr>
        <tr>
            <td>
                Danh mục bài viết
            </td>
            <td>
                <?php
                    $query = \Menus::select();
                    $menus = $query->execute();

                    $name_menu= [];
                    foreach ($menus as $item_menu){
                        /** @var $item_menu \Menus */
                        $name_menu[] = $item_menu->toArray();

                    }
                    function showMenu($menu,$parent_id = 0, $char = ''){
                                foreach ($menu as $key => $item_menu){
                                    if($item_menu['parent'] == $parent_id){
                                        echo '<option value="'.$item_menu['id'].'">';
                                        echo $char.$item_menu['name'];
                                        echo '<option>';
                                        unset($menu[$key]);
                                        showMenu($menu, $item_menu['id'], $char.'|---');
                                    }
                                }
                            }

                       ?>

                <select class="form-control" name="category">
                    <?php showMenu($name_menu); ?>
                </select>
            </td>
        </tr>
        <tr>
            <td colspan="2">
                <button type="submit" style="align-content: center">Thêm mới</button>
            </td>
        </tr>
    </table>

</div>
</form>

