<!--menu header-->

<div class="header ">
    <div class=" pull-left sm-table">
        <div class="header-inner">
            <div class="brand inline">
                <img src="templates/pages.revox.io/assets/img/logo.png" alt="logo" data-src="templates/pages.revox.io/assets/img/logo.png" data-src-retina="templates/pages.revox.io/assets/img/logo_2x.png" width="78" height="22">
            </div>
        </div>
    </div>
    <div class=" pull-right">

       <div class="visible-lg visible-md m-t-10">
            <div class="pull-left p-r-10 p-t-10 fs-16 font-heading">
                <span class="semi-bold"><?php echo $auth->getUsername() ;?></span>
            </div>
            <div class="dropdown pull-right">
                <button class="profile-dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true"
                        aria-expanded="false">
                <span class="thumbnail-wrapper d32 circular inline m-t-5">
                    <img src="<?php echo $auth->getAvatar(32) ?>" alt="" data-src="<?php echo $auth->getAvatar(32) ?>" width="32" height="32" class="">
                </span>
                </button>
                <ul class="dropdown-menu profile-dropdown" role="menu">
                    <?php for ($i = 0, $size = sizeof($items); $i < $size; ++$i) : ?>
                        <?php if($items[$i]['id'] == '_logout'){ ?>
                            <li class="bg-master-lighter _logout">
                                <a href="<?= $items[$i]['url']?>" class="clearfix">
                                    <span class="pull-left"><?= $items[$i]['label']?></span>
                                    <span class="pull-right"><i class="pg-power"></i></span>
                                </a>
                            </li>
                         <?php }else{ ?>
                        <li class="">
                            <a href="<?= $items[$i]['url']?>"><i class="<?= $items[$i]['icon'] ?>"></i><?= $items[$i]['label']?></a>
                        </li>
                    <?php }?>
                    <?php endfor;?>
                </ul>
            </div>
        </div>
    </div>
</div>