<!--menu ben trai cuablank template-->
<!--<div class="sidebar-overlay-slide from-top" id="appMenu">
    <div class="row">
        <div class="col-xs-6 no-padding">
            <a href="#" class="p-l-40"><img src="templates/pages.revox.io/assets/img/demo/social_app.svg" alt="socail"></a>
        </div>
        <div class="col-xs-6 no-padding">
            <a href="#" class="p-l-10"><img src="templates/pages.revox.io/assets/img/demo/email_app.svg" alt="socail"></a>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-6 m-t-20 no-padding">
            <a href="#" class="p-l-40"><img src="templates/pages.revox.io/assets/img/demo/calendar_app.svg" alt="socail"></a>
        </div>
        <div class="col-xs-6 m-t-20 no-padding">
            <a href="#" class="p-l-10"><img src="templates/pages.revox.io/assets/img/demo/add_more.svg" alt="socail"></a>
        </div>
    </div>
</div>-->
<div class="sidebar-header">
    <img src="templates/pages.revox.io/assets/img/logo_white.png" alt="logo" class="brand" data-src="templates/pages.revox.io/assets/img/logo_white.png" data-src-retina="templates/pages.revox.io/assets/img/logo_white_2x.png" width="78" height="22">
    <div class="sidebar-header-controls">
        <button type="button" class="btn btn-xs sidebar-slide-toggle btn-link m-l-20" data-pages-toggle="#appMenu"><i class="fa fa-angle-down fs-16"></i></button>
        <button type="button" class="btn btn-link visible-lg-inline" data-toggle-pin="sidebar"><i class="fa fs-12"></i></button>
    </div>
</div>
<div class="sidebar-menu">
    <ul class="menu-items">
        <?php for ($i = 0, $size = sizeof($items); $i < $size; ++$i) : ?>
            <?php
            $hasChild = (isset($items[$i]['items']) && sizeof($items[$i]['items']) > 0);
            ?>
        <li class="<?php if($items[$i]['label'] == 'Dashboard'){ echo "m-t-30";}?>">
            <a href="<?= $items[$i]['url'] ?>"><span class="title"><?= $items[$i]['label'] ?></span></a>
            <span class="icon-thumbnail <?php if($items[$i]['label'] == 'Dashboard'){ echo "bg-success";} ?>"><i class="<?=$items[$i]['icon']?>"></i></span>
            <?php if ($hasChild): ?>
            <ul class="sub-menu">
                <?php for($j = 0, $sizeOfSub = sizeof($items[$i]['items']); $j < $sizeOfSub; ++$j)
                    :  $child = $items[$i]['items'][$j];?>
                <li class="">
                    <?php
                    $class =  (isset($child['items']))? 'droplink' : '';
                    $class .= ($items[$i]['items'][$j]['active'])? ' current': '';
                    ?>
                    <a href="<?= $items[$i]['items'][$j]['url'] ?>"><?= $items[$i]['items'][$j]['label'] ?></a>
                    <span class="icon-thumbnail"><?=$items[$i]['items'][$j]['icon']?></span>
                    <?php if (isset($child['items'])) :?>
                        <ul class="sub-menu">
                            <?php foreach($child['items'] as $grandchildren) : ?>
                                <li>
                                    <a href="<?php echo $grandchildren['url']?>">
                                        <?php echo $grandchildren['label'];?>
                                    </a>
                                </li>
                            <?php endforeach; ?>
                        </ul>
                    <?php endif; ?>
                </li>
                <?php endfor; ?>
            </ul>
            <?php endif; ?>
        </li>
        <?php endfor; ?>
    </ul>
    <div class="clearfix"></div>
</div>
