<?php
use Flywheel\Document\Html;

/** @var Html $document */
$document = $this->document();
?>
<!DOCTYPE html>
<html>
<head>
    <title>MADARIN</title>

    <!-- ***** meta ***** -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=yes">
    <meta name="keywords" content="premium html template, unique premium template, multipurpose" />
    <meta name="description" content="Welcome to CleanLab Template, a wonderful and premium product for multipurpose websites" />

    <!-- ***** Favicons ***** -->
    <link rel="shortcut icon" href="template_madarin/images/favicon.png">
    <link rel="apple-touch-icon" href="template_madarin/images/favicons/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="44x72" href="template_madarin/images/favicons/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="70x114" href="template_madarin/images/favicons/apple-touch-icon-114x114.png">

    <!-- ***** Google Fonts ***** -->
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>

    <!-- ***** Addons Stylesheet ***** -->
    <link rel="stylesheet" type="text/css" href="template_madarin/css/rev-settings.css" media="screen" />

    <!-- ***** Bootstrap CSS Stylesheet ***** -->
    <link rel="stylesheet" type="text/css" href="template_madarin/css/bootstrap.css">

    <!-- ***** Main + Responsive CSS Stylesheet ***** -->
    <link rel="stylesheet" type="text/css" href="template_madarin/css/icons-styles.css">
    <link rel="stylesheet" type="text/css" href="template_madarin/css/template.css">
    <link rel="stylesheet" type="text/css" href="template_madarin/css/responsive-devices.css" />
    <!-- ***** Updates CSS Stylesheet (for future templates updates ***** -->
    <link rel="stylesheet" type="text/css" href="template_madarin/css/updates.css">
    <!-- ***** Custom CSS Stylesheet (where you should add your own css rules) ***** -->
    <link rel="stylesheet" type="text/css" href="template_madarin/css/custom.css">

    <!-- JS -->
    <script type="text/javascript" src="template_madarin/js/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="template_madarin/js/jquery.min.js">\x3C/script>')</script>
</head>
<body class="">
<div id="page-wrapper">
    <?php $this->widget('app.Widget.MenuMain'); ?>
    <div id="slideshow" class="mbottom70">
        <div class="tp-banner-container">
            <div class="tp-banner" >
                <ul class="reset-list">
                    <!-- SLIDE  -->
                    <li data-transition="slidehorizontal" data-slotamount="7" data-masterspeed="1000"  data-fstransition="fade" data-fsmasterspeed="1000" data-fsslotamount="7">
                        <!-- LAYERS -->
                        <!-- LAYER NR. 1 -->
                        <div class="tp-caption tp-fade fadeout fullscreenvideo"
                             data-x="0"
                             data-y="0"
                             data-speed="1000"
                             data-start="1100"
                             data-easing="Power4.easeOut"
                             data-endspeed="1500"
                             data-endeasing="Power4.easeIn"
                             data-autoplay="true"
                             data-autoplayonlyfirsttime="false"
                             data-nextslideatend="true"
                             data-forceCover="1"
                             data-aspectratio="16:9"
                             data-forcerewind="on"
                             style="z-index: 2">
                            <video class="video-js vjs-default-skin" preload="none">
                                <source src='template_madarin/video/video.mp4' type='video/mp4' />
                                <source src='template_madarin/video/video.webm' type='video/webm' />
                                <source src='template_madarin/video/video.ogg' type='video/ogg' />
                            </video>
                        </div>
                        <!-- LAYER NR. 2 -->
                        <div class="tp-caption large_bold_white_25 customin customout tp-resizeme"
                             data-x="center" data-hoffset="0"
                             data-y="170"
                             data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:5;scaleY:5;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                             data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                             data-speed="600"
                             data-start="1400"
                             data-easing="Power4.easeOut"
                             data-endspeed="600"
                             data-endeasing="Power0.easeIn"
                             style="z-index: 3">"Theo đuổi đam mê <br/> thành công sẽ theo đuổi bạn"
                        </div>
                        <!-- LAYER NR. 3 -->
                        <div class="tp-caption medium_text_shadow customin customout tp-resizeme"
                             data-x="center" data-hoffset="0"
                             data-y="bottom" data-voffset="-140"
                             data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:5;scaleY:5;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                             data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                             data-speed="600"
                             data-start="1700"
                             data-easing="Power4.easeOut"
                             data-endspeed="600"
                             data-endeasing="Power0.easeIn"
                             style="z-index: 4">CEO Đào Thị Trang
                        </div>
                    </li>
                </ul>
                <div class="tp-bannertimer"></div>
            </div>
        </div>
    </div><!-- end slideshow-->
    <div id="content">
        <?php echo $buffer; ?>
    </div><!-- end content -->
    <?php $this->widget('app.Widget.Footer'); ?>
    <!-- end footer -->
</div>
<p id="back-top">
    <a href="#top"><span class="icon-angle-up"></span></a>
</p>


<!-- JavaScript at the bottom for faster page loading -->
<script type="text/javascript" src="template_madarin/js/modernizr.custom.js"></script>
<script type="text/javascript" src="template_madarin/js/bootstrap.js"></script>
<script type="text/javascript" src="template_madarin/js/clean-js-plugins.js"></script>
<!-- CleanLab Scrips File -->
<script type="text/javascript" src="template_madarin/js/cleanlab_script.js"></script>

<!-- Custom Scrips loaded on this page -->
<script type="text/javascript" src="template_madarin/js/jquery.themepunch.plugins.min.js"></script>
<script type="text/javascript" src="template_madarin/js/jquery.themepunch.revolution.min.js"></script>
<script type="text/javascript"> /* Revolution Slider */
    var revapi;
    jQuery(document).ready(function() {
        revapi = jQuery('.tp-banner').revolution(
            {
                delay:9000,
                startwidth:1170,
                startheight:500,
                fullScreen:"on",
                forceFullWidth:"on",
                minFullScreenHeight:"320",
            });
    });	//ready
</script>
<script type="text/javascript"> /* Owl Carousel */
    $(document).ready(function() {
        $("#our-team").owlCarousel({

            autoPlay: 3000, //Set AutoPlay to 3 seconds

            items : 4,
            itemsDesktop : [1199,3],
            itemsDesktopSmall : [979,3],
            autoPlay : false,
            navigation : true,
            pagination : false,
            navigationText: [
                "<i class='icon-angle-left animation'></i>",
                "<i class='icon-angle-right animation'></i>"
            ],
        });
    });
</script>
