<?php
use Flywheel\Document\Html;

/** @var Html $document */
$document = $this->document();
?>
<!DOCTYPE html>
<html>
<head>
    <title>MADARIN</title>

    <!-- ***** meta ***** -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=yes">
    <meta name="keywords" content="premium html template, unique premium template, multipurpose" />
    <meta name="description" content="Welcome to CleanLab Template, a wonderful and premium product for multipurpose websites" />

    <!-- ***** Favicons ***** -->
    <link rel="shortcut icon" href="template_madarin/images/favicon.png">
    <link rel="apple-touch-icon" href="template_madarin/images/favicons/apple-touch-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="44x72" href="template_madarin/images/favicons/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="70x114" href="template_madarin/images/favicons/apple-touch-icon-114x114.png">

    <!-- ***** Google Fonts ***** -->
    <link href='http://fonts.googleapis.com/css?family=Roboto:400,300,300italic,400,400italic,500,500italic,700,700italic' rel='stylesheet' type='text/css'>

    <!-- ***** Addons Stylesheet ***** -->
    <link rel="stylesheet" type="text/css" href="template_madarin/css/rev-settings.css" media="screen" />

    <!-- ***** Bootstrap CSS Stylesheet ***** -->
    <link rel="stylesheet" type="text/css" href="template_madarin/css/bootstrap.css">

    <!-- ***** Main + Responsive CSS Stylesheet ***** -->
    <link rel="stylesheet" type="text/css" href="template_madarin/css/icons-styles.css">
    <link rel="stylesheet" type="text/css" href="template_madarin/css/template.css">
    <link rel="stylesheet" type="text/css" href="template_madarin/css/responsive-devices.css" />
    <!-- ***** Updates CSS Stylesheet (for future templates updates ***** -->
    <link rel="stylesheet" type="text/css" href="template_madarin/css/updates.css">
    <!-- ***** Custom CSS Stylesheet (where you should add your own css rules) ***** -->
    <link rel="stylesheet" type="text/css" href="template_madarin/css/custom.css">

    <!-- JS -->
    <script type="text/javascript" src="template_madarin/js/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="template_madarin/js/jquery.min.js">\x3C/script>')</script>
</head>
<body class="">
<div id="page-wrapper">
    <header id="header" class="nav-down header3">
        <div class="container">
            <div class="row">
                <div class="col-sm-12">
                    <div class="relative onlyh3">
                        <div class="logo-container hasinfocard">
                            <h1 id="logo">
                                <a href="javascript:">
                                    <img src="template_madarin/images/logo.png" alt="CleanLab HTML Template" title="Click to return to CleanLab Template's homepage" class="img-responsive non-transparent">
                                    <img src="template_madarin/images/logo-transparent.png" alt="CleanLab HTML Template" title="Click to return to CleanLab Template's homepage" class="img-responsive only-transparent">
                                </a>
                            </h1><!-- end logo -->
                        </div><!-- end logo-container -->

                        <div class="searchPanel">
                            <span class="icon-search3"></span>
                            <form action="http://www.google.com/search" method="get" onsubmit="Gsitesearch(this)" target="_blank" class="searchForm">
                                <input name="qfront" type="text" placeholder="just type in here..." class="searchBox">
                            </form>
                        </div><!-- end searchPanel -->
                        <div class="dropdown language">
                            <span class=""></span>
                            <div class="dropdown">
							<span class="globe icon-earth" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
							</span>
                                <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                                    <li role="presentation">
                                        <a role="menuitem" tabindex="-1" href="#">English</a>
                                        <img src="template_madarin/images/flags/us.png" alt="English" class="flag-img">
                                    </li>
                                    <li role="presentation">
                                        <a role="menuitem" tabindex="-1" href="#">Spanish</a>
                                        <img src="template_madarin/images/flags/es.png" alt="Việt nam" class="flag-img">
                                    </li>
                                    <li role="presentation">
                                        <a role="menuitem" tabindex="-1" href="#">French</a>
                                        <img src="template_madarin/images/flags/fr.png" alt="Đài loan" class="flag-img">
                                    </li>
                                </ul>
                            </div>
                        </div><!-- end language -->
                        <!-- Responsive Menu -->
                        <div class="zn-res-menuwrapper">
                            <a class="zn-res-trigger" href="#"></a>
                        </div>
                        <div id="main-menu">
                            <ul>
                                <li class="has-sub active">
                                    <a href="#">Trang chủ</a>
                                </li>
                                <li class="has-sub mega">
                                    <a href="index.html">Học Tiếng Trung</a>
                                    <ul class="mega-menu container clearfix">
                                        <li class="col-sm-3">
                                            <a href="http://#" class="mega-title">Homepages examples 1</a>
                                            <ul class="sub-menu clearfix">
                                                <li>
                                                    <a href="home-layout-1.html">Home Layout 1</a>
                                                </li>
                                                <li>
                                                    <a href="home-layout-2.html">Home Layout 2</a>
                                                </li>
                                                <li>
                                                    <a href="home-layout-3.html">Home Layout 3</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="col-sm-3">
                                            <a href="http://#" class="mega-title">Homepages examples 2</a>
                                            <ul class="sub-menu clearfix">
                                                <li>
                                                    <a href="home-layout-4.html">Home Layout 4</a>
                                                </li>
                                                <li>
                                                    <a href="home-layout-5.html">Home Layout 5</a>
                                                </li>
                                                <li>
                                                    <a href="home-layout-6.html">Home Layout 6</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="col-sm-3">
                                            <a href="http://#" class="mega-title">Homepages examples 3</a>
                                            <ul class="sub-menu clearfix">
                                                <li>
                                                    <a href="home-layout-7.html">Home Layout 7</a>
                                                </li>
                                                <li>
                                                    <a href="home-layout-8.html">Home Layout 8</a>
                                                </li>
                                                <li>
                                                    <a href="home-layout-9.html">Home Layout 9</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="col-sm-3">
                                            <a href="http://#" class="mega-title">Homepages examples 4</a>
                                            <ul class="sub-menu clearfix">
                                                <li>
                                                    <a href="home-layout-10.html">Home Layout 10</a>
                                                </li>
                                                <li>
                                                    <a href="one-page.html">One Page</a>
                                                </li>
                                                <li>
                                                    <a href="full-page.html">Full Page</a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>

                                <li class="has-sub">
                                    <a href="#">VIỆT NEWS</a>
                                    <ul>
                                        <li>
                                            <a href="portfolio.html">Portfolio</a>
                                        </li>
                                        <li>
                                            <a href="portfolio-simple.html">Portfolio Simple Layout</a>
                                        </li>
                                        <li>
                                            <a href="portfolio-full-width.html">Portfolio - Full Width</a>
                                        </li>
                                        <li>
                                            <a href="single-project.html">Single Project</a>
                                        </li>
                                    </ul>
                                </li>
                                <li>
                                    <a href="#">ĐÀI LOAN NEWS</a>
                                    <ul>
                                        <li>
                                            <a href="blog.html">Blog Style 1</a>
                                        </li>
                                        <li>
                                            <a href="blog-2.html">Blog Style 2</a>
                                        </li>
                                        <li>
                                            <a href="blog-3.html">Blog Style 3</a>
                                        </li>
                                        <li>
                                            <a href="blog-4.html">Blog Style 4</a>
                                        </li>
                                        <li>
                                            <a href="blog-timeline.html">Timeline Blog</a>
                                        </li>
                                        <li>
                                            <a href="blog-masonry.html">Masonry Blog</a>
                                        </li>
                                        <li>
                                            <a href="blog-masonry-full.html">Masonry Blog Full</a>
                                        </li>
                                        <li>
                                            <a href="blog-post.html">Blog Post Style 1</a>
                                        </li>
                                        <li>
                                            <a href="blog-post-2.html">Blog Post Style 2</a>
                                        </li>
                                    </ul>
                                </li>
                                <li class="has-sub mega">
                                    <a href="contact.html">LIÊN HỆ</a>
                                    <ul class="mega-menu container clearfix hidden">
                                        <li class="col-sm-3">
                                            <a href="http://#" class="mega-title">Pages examples 1</a>
                                            <ul class="sub-menu clearfix">
                                                <li>
                                                    <a href="full-width-page.html">Full Width</a>
                                                </li>
                                                <li>
                                                    <a href="left-sidebar-page.html">Left Sidebar</a>
                                                </li>
                                                <li>
                                                    <a href="right-sidebar-page.html">Right Sidebar</a>
                                                </li>
                                                <li>
                                                    <a href="text-page.html">Text Page</a>
                                                </li>
                                                <li>
                                                    <a href="product-launch.html">Product Launch</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="col-sm-3">
                                            <a href="http://#" class="mega-title">Pages examples 2</a>
                                            <ul class="sub-menu clearfix">
                                                <li>
                                                    <a href="faq.html">FAQ</a>
                                                </li>
                                                <li>
                                                    <a href="testimonials.html">Testimonials</a>
                                                </li>
                                                <li>
                                                    <a href="features.html">Features</a>
                                                </li>
                                                <li>
                                                    <a href="our-office.html">Our Office</a>
                                                </li>
                                                <li>
                                                    <a href="pricing.html">Pricing</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="col-sm-3">
                                            <a href="http://#" class="mega-title">Pages examples 3</a>
                                            <ul class="sub-menu clearfix">
                                                <li>
                                                    <a href="timeline-page.html">Timeline Page</a>
                                                </li>
                                                <li>
                                                    <a href="clients.html">Clients</a>
                                                </li>
                                                <li>
                                                    <a href="team.html">Our Team</a>
                                                </li>
                                                <li>
                                                    <a href="team-member.html">Team Member</a>
                                                </li>
                                                <li>
                                                    <a href="about-us.html">About us</a>
                                                </li>
                                            </ul>
                                        </li>
                                        <li class="col-sm-3">
                                            <a href="http://#" class="mega-title">Pages examples 4</a>
                                            <ul class="sub-menu clearfix">
                                                <li>
                                                    <a href="coming-soon.html">Coming Soon</a>
                                                </li>
                                                <li>
                                                    <a href="maintenance-mode.html">Maintenance Mode</a>
                                                </li>
                                                <li>
                                                    <a href="contact.html">Contact Page</a>
                                                </li>
                                                <li>
                                                    <a href="sitemap.html">Sitemap</a>
                                                </li>
                                                <li>
                                                    <a href="404.html">404 Error Page</a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                </li>
                                <!--<li class="has-sub">
                                       <a href="#">Shop</a>
                                       <ul>
                                              <li>
                                                <a href="shop-home.html">Home Page</a>
                                           <li>
                                           <li>
                                                    <a href="product.html">Product Item</a>
                                             </li>
                                              <li>
                                                    <a href="shopping-cart.html">Shopping Cart</a>
                                             </li>
                                             <li>
                                                    <a href="shop-order-recieved.html">Order Confirmation</a>
                                             </li>
                                             <li>
                                                    <a href="shop-account-login.html">My Account - Login</a>
                                             </li>
                                       </ul>
                                </li>-->
                                <!--<li>
                                       <a href="bootstrap.html">Features</a>
                                       <ul>
                                           <li>
                                               <a href="builder/index.html">Page Builder</a>
                                           </li>
                                           <li>
                                               <a href="gallery-1.html">Gallery 1 column</a>
                                           </li>
                                           <li>
                                               <a href="gallery-2.html">Gallery 2 column</a>
                                           </li>
                                           <li>
                                               <a href="gallery-3.html">Gallery 3 column</a>
                                           </li>
                                           <li>
                                               <a href="gallery-4.html">Gallery 4 column</a>
                                           </li>
                                           <li>
                                               <a href="gallery-masonry.html">Gallery - Masonry</a>
                                           </li>
                                           <li>
                                               <a href="gallery-masonry-full.html">Gallery Full - Masonry</a>
                                           </li>
                                       </ul>
                                </li>-->
                                <!--<li>
                                       <a href="#">Shortcodes</a>
                                       <ul>
                                           <li>
                                                     <a href="typography.html">Typography</a>
                                              </li>
                                              <li>
                                                     <a href="page-header.html">Page Header</a>
                                              </li>
                                              <li>
                                                     <a href="media-player.html">Media Player</a>
                                              </li>
                                              <li>
                                                     <a href="gallery.html">Gallery</a>
                                              </li>
                                              <li>
                                            <a href="services-box.html">Services Box</a>
                                        </li>
                                              <li>
                                                     <a href="buttons.html">Buttons</a>
                                              </li>
                                              <li>
                                                     <a href="progress-bars.html">Progress Bars & Skill Meter</a>
                                              </li>
                                              <li>
                                                     <a href="tabs.html">Tabs</a>
                                              </li>
                                              <li>
                                                     <a href="google-maps.html">Google Maps</a>
                                              </li>
                                              <li>
                                                     <a href="accordion.html">Accordion & Toggles</a>
                                              </li>
                                              <li>
                                                     <a href="callout-box.html">Custom Callout Box</a>
                                              </li>
                                              <li>
                                                     <a href="laptop-slider.html">Laptop Slider</a>
                                              </li>
                                              <li>
                                                     <a href="image-shadows.html">Image Shadows</a>
                                              </li>
                                       </ul>
                               </li>-->
                            </ul>
                        </div><!-- end main menu -->
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div id="slideshow" class="mbottom70">
        <div class="tp-banner-container">
            <div class="tp-banner" >
                <ul class="reset-list">
                    <!-- SLIDE  -->
                    <li data-transition="slidehorizontal" data-slotamount="7" data-masterspeed="1000"  data-fstransition="fade" data-fsmasterspeed="1000" data-fsslotamount="7">
                        <!-- LAYERS -->
                        <!-- LAYER NR. 1 -->
                        <div class="tp-caption tp-fade fadeout fullscreenvideo"
                             data-x="0"
                             data-y="0"
                             data-speed="1000"
                             data-start="1100"
                             data-easing="Power4.easeOut"
                             data-endspeed="1500"
                             data-endeasing="Power4.easeIn"
                             data-autoplay="true"
                             data-autoplayonlyfirsttime="false"
                             data-nextslideatend="true"
                             data-forceCover="1"
                             data-aspectratio="16:9"
                             data-forcerewind="on"
                             style="z-index: 2">
                            <video class="video-js vjs-default-skin" preload="none">
                                <source src='template_madarin/video/video.mp4' type='video/mp4' />
                                <source src='template_madarin/video/video.webm' type='video/webm' />
                                <source src='template_madarin/video/video.ogg' type='video/ogg' />
                            </video>
                        </div>
                        <!-- LAYER NR. 2 -->
                        <div class="tp-caption large_bold_white_25 customin customout tp-resizeme"
                             data-x="center" data-hoffset="0"
                             data-y="170"
                             data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:5;scaleY:5;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                             data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                             data-speed="600"
                             data-start="1400"
                             data-easing="Power4.easeOut"
                             data-endspeed="600"
                             data-endeasing="Power0.easeIn"
                             style="z-index: 3">"Theo đuổi đam mê <br/> thành công sẽ theo đuổi bạn"
                        </div>
                        <!-- LAYER NR. 3 -->
                        <div class="tp-caption medium_text_shadow customin customout tp-resizeme"
                             data-x="center" data-hoffset="0"
                             data-y="bottom" data-voffset="-140"
                             data-customin="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:5;scaleY:5;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                             data-customout="x:0;y:0;z:0;rotationX:0;rotationY:0;rotationZ:0;scaleX:0.75;scaleY:0.75;skewX:0;skewY:0;opacity:0;transformPerspective:600;transformOrigin:50% 50%;"
                             data-speed="600"
                             data-start="1700"
                             data-easing="Power4.easeOut"
                             data-endspeed="600"
                             data-endeasing="Power0.easeIn"
                             style="z-index: 4">CEO Đào Thị Trang
                        </div>
                    </li>
                </ul>
                <div class="tp-bannertimer"></div>
            </div>
        </div>
    </div><!-- end slideshow-->
    <div id="content">
        <?php echo $buffer; ?>
    </div><!-- end content -->
    <footer class="footer-style2">
        <div class="container">
            <div class="row">
                <div class="col-sm-3 mbottom30">
                    <a href="index.html">
                        <img src="template_madarin/images/footer-logo.png" alt="" class="default" />
                        <img src="template_madarin/images/footer-logo2.png" alt="" class="only3" />
                    </a>
                    <p class="mtop30">Etiam accumsan tristique diam, nec mollis nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
                    <div class="social mtop25 mbottom30 clearfix">
                        <ul class="reset-list">
                            <li class="ico-twitter animation">
                                <a href="#">
                                    <span class="icon-twitter"></span>
                                </a>
                            </li>
                            <li class="ico-facebook animation">
                                <a href="#">
                                    <span class="icon-facebook"></span>
                                </a>
                            </li>
                            <li class="ico-google animation">
                                <a href="#">
                                    <span class="icon-googleplus"></span>
                                </a>
                            </li>
                            <li class="ico-pinterest animation">
                                <a href="#">
                                    <span class="icon-pinterest"></span>
                                </a>
                            </li>
                            <li class="ico-dribbble animation">
                                <a href="#">
                                    <span class="icon-dribbble"></span>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="col-sm-3 mbottom30">
                    <h3>Blogger</h3>
                    <ul class="footer-blog reset-list">
                        <li>
                            <a href="blog-post.html">
                                <img src="template_madarin/images/footer-img.jpg" alt=""/>
                            </a>
                            <p>Cảm nhận về văn hóa Việt</p>
                            <p class="tcolor">June 22, 2013</p>
                            <div class="clearfix mbottom20"></div>
                        </li>
                        <li>
                            <a href="blog-post.html">
                                <img src="template_madarin/images/footer-img2.jpg" alt=""/>
                            </a>
                            <p>Cảm nhận về văn hóa Đài Loan</p>
                            <p class="tcolor">June 22, 2013</p>
                            <div class="clearfix"></div>
                        </li>
                    </ul>
                </div>
                <div class="col-sm-3 mbottom30">
                    <h3>MADARIN</h3>
                    <ul class="menu-list reset-list">
                        <li>
                            <a href="#">Chúng tôi</a>
                        </li>
                        <li>
                            <a href="contact.html">Liên hệ</a>
                        </li>
                        <li>
                            <a href="#">Chính sách</a>
                        </li>
                        <li>
                            <a href="#">Mục tiêu</a>
                        </li>
                        <!--<li>
                            <a href="testimonials.html">Testimonials</a>
                        </li>-->
                    </ul>
                </div>
                <div class="col-sm-3">
                    <h3>Gửi phản hồi</h3>
                    <div id="subscribe" class="footer-subscribe center mbottom10">
                        <form action="http://lorthemes.us8.list-manage1.com/subscribe/post-json?u=42795504a248e486766e563b9&amp;id=f766078320&amp;c=?" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                            <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="" required>
                            <div style="position: absolute; left: -5000px;">
                                <input type="text" name="b_9ed253451c5b914e9c34e388b_6e3ba686ba" value="">
                            </div>
                            <button class=" btn-sm btn-small" type="submit" name="subscribe" id="mc-embedded-subscribe"><span class="icon-envelope"></span></button>
                        </form>
                        <div id="notification_container"></div>
                    </div>
                    <p>By subscribing to our mailing list you will always be update with the latest news from us.</p>
                </div>
            </div>
        </div>
        <div class="bottom-footer">
            <div class="container">
                <div class="row ptop10">
                    <div class="col-sm-6 col-xs-12 mbottom20">
                        <p class="copyright">© 2014 - 2015 developed by <strong>Nguyễn Hoàng Giang</strong>. All Rights Reserved</p>
                    </div>
                    <div class="col-sm-6 col-xs-12">
                        <div class="social-buttons">
                            <div class="facebook-button">
                                <!-- Change this iframe with your own. -->
                                <iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2FEnvatoStudio&amp;width&amp;layout=button_count&amp;action=like&amp;show_faces=false&amp;share=false&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:21px;" allowTransparency="true"></iframe>
                            </div>
                            <div class="twitter-button">
                                <!-- Change data-via to your own. -->
                                <a href="https://twitter.com/share" class="twitter-share-button" data-via="BogdanStw">Tweet</a>
                                <script>
                                    !function(d,s,id){
                                        var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';
                                        if(!d.getElementById(id)){
                                            js=d.createElement(s);
                                            js.id=id;
                                            js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
                                </script>
                            </div>
                            <div class="google-button">
                                <!-- Place this tag where you want the +1 button to render. -->
                                <div class="g-plusone" data-size="medium"></div>
                                <!-- Place this tag after the last +1 button tag. -->
                                <script type="text/javascript">
                                    (function() {
                                            var po = document.createElement('script');
                                            po.type = 'text/javascript';
                                            po.async = true;
                                            po.src = 'https://apis.google.com/js/plusone.js';
                                            var s = document.getElementsByTagName('script')[0];
                                            s.parentNode.insertBefore(po, s);
                                        }
                                    )();
                                </script>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!-- end footer -->
</div>
<p id="back-top">
    <a href="#top"><span class="icon-angle-up"></span></a>
</p>


<!-- JavaScript at the bottom for faster page loading -->
<script type="text/javascript" src="template_madarin/js/modernizr.custom.js"></script>
<script type="text/javascript" src="template_madarin/js/bootstrap.js"></script>
<script type="text/javascript" src="template_madarin/js/clean-js-plugins.js"></script>
<!-- CleanLab Scrips File -->
<script type="text/javascript" src="template_madarin/js/cleanlab_script.js"></script>

<!-- Custom Scrips loaded on this page -->
<script type="text/javascript" src="template_madarin/js/jquery.themepunch.plugins.min.js"></script>
<script type="text/javascript" src="template_madarin/js/jquery.themepunch.revolution.min.js"></script>
<script type="text/javascript"> /* Revolution Slider */
    var revapi;
    jQuery(document).ready(function() {
        revapi = jQuery('.tp-banner').revolution(
            {
                delay:9000,
                startwidth:1170,
                startheight:500,
                fullScreen:"on",
                forceFullWidth:"on",
                minFullScreenHeight:"320",
            });
    });	//ready
</script>
<script type="text/javascript"> /* Owl Carousel */
    $(document).ready(function() {
        $("#our-team").owlCarousel({

            autoPlay: 3000, //Set AutoPlay to 3 seconds

            items : 4,
            itemsDesktop : [1199,3],
            itemsDesktopSmall : [979,3],
            autoPlay : false,
            navigation : true,
            pagination : false,
            navigationText: [
                "<i class='icon-angle-left animation'></i>",
                "<i class='icon-angle-right animation'></i>"
            ],
        });
    });
</script>
<!-- Google Analytics: change UA-XXXXX-X to be your site's ID.

</body>
</html>