<?php

namespace Mongodb;

/**
 * Mongodb\ItemsSalePriceFile document.
 */
class ItemsSalePriceFile extends \Mongodb\Base\ItemsSalePriceFile
{
    protected static $_pool = [];
    /**
     * Retrieve by Id
     *
     * @param $id
     * @return \Mongodb\ItemsSalePriceFile|null
     */
    public static function retrieveById($id)
    {
        if ($obj = self::getInstanceFromPool($id)) {
            return $obj;
        }

        $repo = new ItemsSalePriceFileRepository(ConnectMongoDB::getConnection());
        $obj = $repo->findOneById($id);
        if ($obj) {
            self::addInstanceToPool($obj, $id);
        }

        return $obj;
    }

    /**
     * Save the document.
     *
     * @param array $options The options for the batch insert or update operation, it depends on if the document is new or not (optional).
     *
     * @return \Mandango\Document\Document The document (fluent interface).
     *
     * @api
     */
    public function save(array $options = array())
    {
        $obj = parent::save($options); // TODO: Change the autogenerated stub
        self::addInstanceToPool($obj, $obj->getId()->{'$id'});
        return $this;
    }


    /**
     * retrieve instance from static
     *
     * @param $id
     * @return null | \Mongodb\ItemsSalePriceFile
     */
    public static function getInstanceFromPool($id)
    {
        return isset(self::$_pool[$id])? self::$_pool[$id] : null;
    }

    /**
     * @param $obj
     * @param $id
     */
    public static function addInstanceToPool($obj, $id)
    {
        self::$_pool[$id] = $obj;
    }
}