<?php
use Flywheel\Document\Html;

/** @var Html $document */
$document = $this->document();
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"/>
    <meta name="apple-mobile-web-app-capable" content="yes"/>
    <meta names="apple-mobile-web-app-status-bar-style" content="black-translucent"/>
    <title><?php echo $document->title; ?></title>
    <base href="<?php echo $document->getBaseUrl() ?>">
    <?php echo $document->css(); ?>
    <?php echo $document->js('TOP'); ?>
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <!--------phần css-------->
    <link rel="apple-touch-icon" href="templates/pages.revox.io/pages/ico/60.png">
    <link rel="apple-touch-icon" sizes="76x76" href="templates/pages.revox.io/pages/ico/76.png">
    <link rel="apple-touch-icon" sizes="120x120" href="templates/pages.revox.io/pages/ico/120.png">
    <link rel="apple-touch-icon" sizes="152x152" href="templates/pages.revox.io/pages/ico/152.png">
    <link rel="shortcut icon" href="templates/pages.revox.io/assets/img/favicon.ico" />
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-touch-fullscreen" content="yes">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">
    <meta content="" name="description"/>
    <meta content="" name="author"/>
    <!--------phan Js-------->
    <script type="text/javascript">
        window.onload = function () {
            // fix for windows 8
            if (navigator.appVersion.indexOf("Windows NT 6.2") != -1)
                document.head.innerHTML += '<link rel="stylesheet" type="text/css" href="pages/css/windows.chrome.fix.css" />'
        }
    </script>
    <link rel="apple-touch-icon-precomposed" href="img/apple-touch-icon-precomposed.png"/>
</head>
<body class="fixed-header">
<nav class="page-sidebar" data-pages="sidebar">
    <?php $this->widget('app.Widget.Navigator'); ?> <!--widget menu bên trái của giao diện-->

</nav>
<div class="page-container">
    <?php $this->widget('app.Widget.HeaderMenu'); ?><!--menu header của menu, chưa search , hình ảnh....-->

    <div class="page-content-wrapper">
        <div class="content">
            <?php echo $buffer ?>
        </div>
        <div class="container-fluid container-fixed-lg footer">
            <div class="copyright sm-text-center">
                <p class="small no-margin pull-left sm-pull-reset">
                    <span class="hint-text">Copyright © 2015 </span>
                    <span class="font-montserrat">Madarin Việt Nam</span>.
                    <span class="hint-text">All rights reserved. </span>
                </p>
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
</div>
<?php echo $document->js('BOTTOM'); ?>
</body>
</html>