<?php
/** @var  $detail \News */


?>


<div class="container">
    <div class="row">
        <div class="col-sm-9">
            <div class="blog-post mbottom50">
                <!--<img src="images/blog/img12.jpg" alt="" class="img-responsive mbottom30">-->
                <div class="post-head mbottom30">
                    <h2><?php echo $detail['title'] ?></h2>
                    <span class="tcolor">June 22, 2013</span>
                    <span class="icon-heart2 mleft10"><b>17</b></span>
                    <span class="icon-bubbles4 mleft10 mright10"><b class="mleft5">28</b></span>
                    <span class="italic">people, marketing</span>
                </div>
                <div class="post-content">
                    <?php echo $detail['content'] ?>
                </div>
            </div>
            <div class="separator mbottom50"></div>
        </div>
        <?php $this->widget('app.Widget.Categorys'); ?>
    </div>
</div>