<div class="container">
    <div class="row">
        <div class="col-sm-9">
            <div class="blog-post mbottom50">
                <!--<img src="images/blog/img12.jpg" alt="" class="img-responsive mbottom30">-->
                <div class="post-head mbottom30">
                    <h2>Aliquam accumsan mattis diam, eu dapibus purus tristique convallis. Donec arcu nisi, iaculis a feugiat vitae, mollis non urna. Vestibulum erat diam, pretium non commodo eu.</h2>
                    <span class="tcolor">June 22, 2013</span>
                    <span class="icon-heart2 mleft10"><b>17</b></span>
                    <span class="icon-bubbles4 mleft10 mright10"><b class="mleft5">28</b></span>
                    <span class="italic">people, marketing</span>
                </div>
                <div class="post-content">
                    <p class="mbottom20">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur.</p>
                    <p class="mbottom20">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </p>
                    <p class="mbottom20">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </p>
                    <p class="mbottom20">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </p>
                    <p class="mbottom20">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </p>
                    <p class="mbottom20">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </p>
                    <p class="mbottom20">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </p>
                    <p class="mbottom20">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </p>
                    <p class="mbottom20">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </p>
                    <p class="mbottom20">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </p>
                    <p class="mbottom20">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </p>
                    <p class="mbottom20">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </p>
                    <p class="mbottom20">Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. </p>
                </div>
            </div>
            <div class="separator mbottom50"></div>
        </div>
        <div class="col-sm-3">
            <div class="sidebar mbottom50">
                <div class="advertisment mbottom50">
                    <p>Advertisment</p>
                    <img src="images/advertisment.jpg" alt="" class="img-responsive" />
                </div>
                <div class="widget-categories mbottom50">
                    <h3>Categories</h3>
                    <ul class="reset-list">
                        <li>
                            <a href="#">Web Design</a>
                        </li>
                        <li>
                            <a href="#">Web Development</a>
                        </li>
                        <li>
                            <a href="#">Marketing</a>
                        </li>
                        <li>
                            <a href="#">Tips</a>
                        </li>
                        <li>
                            <a href="#">Resources</a>
                        </li>
                        <li>
                            <a href="#">Illustration</a>
                        </li>
                    </ul>
                </div>
                <div class="widget-tags mbottom50">
                    <h3>Tags</h3>
                    <ul class="reset-list">
                        <li>
                            <a href="#">design</a>
                        </li>
                        <li>
                            <a href="#">development</a>
                        </li>
                        <li>
                            <a href="#">marketing</a>
                        </li>
                        <li>
                            <a href="#">project</a>
                        </li>
                        <li>
                            <a href="#">inspiration</a>
                        </li>
                        <li>
                            <a href="#">tutorials</a>
                        </li>
                        <li>
                            <a href="#">interviews</a>
                        </li>
                        <li>
                            <a href="#">web</a>
                        </li>
                        <li>
                            <a href="#">wordpress</a>
                        </li>
                        <li>
                            <a href="#">links</a>
                        </li>
                        <li>
                            <a href="#">resources</a>
                        </li>
                    </ul>
                </div>
                <div class="advertisment2">
                    <p>Advertisment</p>
                    <img src="images/advertisment2.jpg" alt="" class="img-responsive" />
                    <img src="images/advertisment2.jpg" alt="" class="img-responsive" />
                    <img src="images/advertisment2.jpg" alt="" class="img-responsive" />
                    <img src="images/advertisment2.jpg" alt="" class="img-responsive" />
                    <div class="clearfix"></div>
                </div>
            </div><!-- end sidebar -->
            <div class="sidebar2 mbottom50">
                <h2 class="section-title3 mbottom30">Featured News</h2>
                <ul class="mbottom50 reset-list">
                    <li class="clearfix">
                        <img src="images/blog/small1.jpg" alt="" />
                        <a href="#"><h4>Fusce dapibus, tellus ac cursus</h4></a>
                        <span class="tag">design, illustration</span>
                        <span class="icon-heart2 mleft10"><b>17</b></span>
                        <span class="icon-bubbles4 mleft10"><b class="mleft5">28</b></span>
                    </li>
                    <li class="clearfix">
                        <img src="images/blog/small2.jpg" alt="" />
                        <a href="#"><h4>Lorem ipsum dolor sit amet, consectetur</h4></a>
                        <span class="tag">people, marketing</span>
                        <span class="icon-heart2 mleft10"><b>11</b></span>
                        <span class="icon-bubbles4 mleft10"><b class="mleft5">18</b></span>
                    </li>
                    <li class="clearfix">
                        <img src="images/blog/small3.jpg" alt="" />
                        <a href="#"><h4>Voluptatem sequi nesciun</h4></a>
                        <span class="tag">design, illustration</span>
                        <span class="icon-heart2 mleft10"><b>19</b></span>
                        <span class="icon-bubbles4 mleft10"><b class="mleft5">35</b></span>
                    </li>
                    <li class="clearfix">
                        <img src="images/blog/small4.jpg" alt="" />
                        <a href="#"><h4>Fusce dapibus, tellus ac cursus</h4></a>
                        <span class="tag">people, marketing</span>
                        <span class="icon-heart2 mleft10"><b>21</b></span>
                        <span class="icon-bubbles4 mleft10"><b class="mleft5">25</b></span>
                    </li>
                    <li class="clearfix">
                        <img src="images/blog/small5.jpg" alt="" />
                        <a href="#"><h4>Voluptatem sequi nesciunt</h4></a>
                        <span class="tag">tips</span>
                        <span class="icon-heart2 mleft10"><b>10</b></span>
                        <span class="icon-bubbles4 mleft10"><b class="mleft5">41</b></span>
                    </li>
                </ul>
            </div><!-- end sidebar2 -->
        </div>
    </div>
</div>