<style>
   .services4-boxes {background: #fafafa;}
</style>
<div class="container mbottom100">

   <div class="row">
      <div class="col-sm-3">
         <div class="services4-boxes center">
            <h3>News</h3>
            <span class="icon-images"></span>
            <p>Donec ullamcorper nulla non ms ac is mollis, est non commodo luctus, nisi ula.</p>
         </div>
      </div>
      <div class="col-sm-3 background-font">
         <div class="services4-boxes center">
            <h3>Học Tiếng Trung</h3>
            <span class="icon-lamp3"></span>
            <p>Donec ullamcorper nulla non ms ac is mollis, est non commodo luctus, nisi ula.</p>
         </div>
      </div>
      <div class="col-sm-3 background-font">
         <div class="services4-boxes center">
            <h3>Học Tiếng Việt</h3>
            <span class="icon-lamp3"></span>
            <p>Donec ullamcorper nulla non ms ac is mollis, est non commodo luctus, nisi ula.</p>
         </div>
      </div>

      <div class="col-sm-3">
         <div class="services4-boxes center">
            <h3>Blogger</h3>
            <span class="icon-pen"></span>
            <p>Donec ullamcorper nulla non ms ac is mollis, est non commodo luctus, nisi ula.</p>
         </div>
      </div>
   </div>
</div><!-- end services -->
<div class="container ptop50 pbottom70" style="padding-top:0px !important;">
   <h2 class="section-title mbottom50">What's New?</h2>
   <div class="row">
      <div class="col-sm-3">
         <div class="news-boxes mbottom35">
            <div class="news-header">
               <span>10</span>
               <span>08</span>
               <h3>Hơn 60 tấn ngao chết trắng biển Hà Tĩnh</h3>
            </div>
            <p class="mbottom30">Donec ullamcorper nulla non ms ac is mollis, est non commodo luctus, nisi ula, eget lacinia odio sem nec elit. Aene ndum nulla sed. Donec ullamcorper nulla non metus ac is mollis, est non commodo luctus.</p>
            <a href="#">More info</a>
         </div>
      </div>
      <div class="col-sm-3">
         <div class="news-boxes mbottom35">
            <div class="news-header">
               <span>10</span>
               <span>07</span>
               <h3>春夏季新款婚纱礼服新娘结婚韩式双肩长拖尾婚纱一字肩</h3>
            </div>
            <p class="mbottom30">Donec ullamcorper nulla non ms ac is mollis, est non commodo luctus, nisi ula, eget lacinia odio sem nec elit. Aene ndum nulla sed. Donec ullamcorper nulla non metus ac is mollis, est non commodo luctus.</p>
            <a href="#">More info</a>
         </div>
      </div>
      <div class="col-sm-3">
         <div class="news-boxes mbottom35">
            <div class="news-header">
               <span>10</span>
               <span>08</span>
               <h3>Hơn 60 tấn ngao chết trắng biển Hà Tĩnh</h3>
            </div>
            <p class="mbottom30">Donec ullamcorper nulla non ms ac is mollis, est non commodo luctus, nisi ula, eget lacinia odio sem nec elit. Aene ndum nulla sed. Donec ullamcorper nulla non metus ac is mollis, est non commodo luctus.</p>
            <a href="#">More info</a>
         </div>
      </div>
      <div class="col-sm-3">
         <div class="news-boxes mbottom35">
            <div class="news-header">
               <span>10</span>
               <span>07</span>
               <h3>春夏季新款婚纱礼服新娘结婚韩式双肩长拖尾婚纱一字肩</h3>
            </div>
            <p class="mbottom30">Donec ullamcorper nulla non ms ac is mollis, est non commodo luctus, nisi ula, eget lacinia odio sem nec elit. Aene ndum nulla sed. Donec ullamcorper nulla non metus ac is mollis, est non commodo luctus.</p>
            <a href="#">More info</a>
         </div>
      </div>
   </div>
</div><!-- end news -->
<div id="team" class="ptop50 pbottom80 hidden">
   <div class="container">
      <div class="row">
         <div class="col-sm-12 relative">
            <h2 class="section-title">Meet Our Team of Best Professionals</h2>
            <div id="our-team">
               <div class="item overlay overlay-effect">
                  <figure>
                     <a href="team-member.html">
                        <img src="images/team/img1.jpg" alt="" class="img-responsive" />
                     </a>
                     <figcaption>
                        <h3>Mark Anthony</h3>
                        <h5>UI/UX Designer</h5>
                        <ul class="reset-list">
                           <li class="ico-twitter animation">
                              <a href="#">
                                 <span class="icon-twitter"></span>
                              </a>
                           </li>
                           <li class="ico-facebook animation">
                              <a href="#">
                                 <span class="icon-facebook"></span>
                              </a>
                           </li>
                           <li class="ico-pinterest animation">
                              <a href="#">
                                 <span class="icon-pinterest"></span>
                              </a>
                           </li>
                           <li class="ico-instagram animation">
                              <a href="#">
                                 <span class="icon-instagram"></span>
                              </a>
                           </li>
                           <li class="ico-dribbble animation">
                              <a href="#">
                                 <span class="icon-dribbble"></span>
                              </a>
                           </li>
                        </ul>
                     </figcaption>
                  </figure>
               </div>
               <div class="item overlay overlay-effect">
                  <figure>
                     <a href="team-member.html">
                        <img src="images/team/img2.jpg" alt="" class="img-responsive" />
                     </a>
                     <figcaption>
                        <h3>Mark Anthony</h3>
                        <h5>UI/UX Designer</h5>
                        <ul class="reset-list">
                           <li class="ico-twitter animation">
                              <a href="#">
                                 <span class="icon-twitter"></span>
                              </a>
                           </li>
                           <li class="ico-facebook animation">
                              <a href="#">
                                 <span class="icon-facebook"></span>
                              </a>
                           </li>
                           <li class="ico-pinterest animation">
                              <a href="#">
                                 <span class="icon-pinterest"></span>
                              </a>
                           </li>
                           <li class="ico-instagram animation">
                              <a href="#">
                                 <span class="icon-instagram"></span>
                              </a>
                           </li>
                           <li class="ico-dribbble animation">
                              <a href="#">
                                 <span class="icon-dribbble"></span>
                              </a>
                           </li>
                        </ul>
                     </figcaption>
                  </figure>
               </div>
               <div class="item overlay overlay-effect">
                  <figure>
                     <a href="team-member.html">
                        <img src="images/team/img3.jpg" alt="" class="img-responsive" />
                     </a>
                     <figcaption>
                        <h3>Mark Anthony</h3>
                        <h5>UI/UX Designer</h5>
                        <ul class="reset-list">
                           <li class="ico-twitter animation">
                              <a href="#">
                                 <span class="icon-twitter"></span>
                              </a>
                           </li>
                           <li class="ico-facebook animation">
                              <a href="#">
                                 <span class="icon-facebook"></span>
                              </a>
                           </li>
                           <li class="ico-pinterest animation">
                              <a href="#">
                                 <span class="icon-pinterest"></span>
                              </a>
                           </li>
                           <li class="ico-instagram animation">
                              <a href="#">
                                 <span class="icon-instagram"></span>
                              </a>
                           </li>
                           <li class="ico-dribbble animation">
                              <a href="#">
                                 <span class="icon-dribbble"></span>
                              </a>
                           </li>
                        </ul>
                     </figcaption>
                  </figure>
               </div>
               <div class="item overlay overlay-effect">
                  <figure>
                     <a href="team-member.html">
                        <img src="images/team/img4.jpg" alt="" class="img-responsive" />
                     </a>
                     <figcaption>
                        <h3>Mark Anthony</h3>
                        <h5>UI/UX Designer</h5>
                        <ul class="reset-list">
                           <li class="ico-twitter animation">
                              <a href="#">
                                 <span class="icon-twitter"></span>
                              </a>
                           </li>
                           <li class="ico-facebook animation">
                              <a href="#">
                                 <span class="icon-facebook"></span>
                              </a>
                           </li>
                           <li class="ico-pinterest animation">
                              <a href="#">
                                 <span class="icon-pinterest"></span>
                              </a>
                           </li>
                           <li class="ico-instagram animation">
                              <a href="#">
                                 <span class="icon-instagram"></span>
                              </a>
                           </li>
                           <li class="ico-dribbble animation">
                              <a href="#">
                                 <span class="icon-dribbble"></span>
                              </a>
                           </li>
                        </ul>
                     </figcaption>
                  </figure>
               </div>
               <div class="item overlay overlay-effect">
                  <figure>
                     <a href="team-member.html">
                        <img src="images/team/img1.jpg" alt="" class="img-responsive" />
                     </a>
                     <figcaption>
                        <h3>Mark Anthony</h3>
                        <h5>UI/UX Designer</h5>
                        <ul class="reset-list">
                           <li class="ico-twitter animation">
                              <a href="#">
                                 <span class="icon-twitter"></span>
                              </a>
                           </li>
                           <li class="ico-facebook animation">
                              <a href="#">
                                 <span class="icon-facebook"></span>
                              </a>
                           </li>
                           <li class="ico-pinterest animation">
                              <a href="#">
                                 <span class="icon-pinterest"></span>
                              </a>
                           </li>
                           <li class="ico-instagram animation">
                              <a href="#">
                                 <span class="icon-instagram"></span>
                              </a>
                           </li>
                           <li class="ico-dribbble animation">
                              <a href="#">
                                 <span class="icon-dribbble"></span>
                              </a>
                           </li>
                        </ul>
                     </figcaption>
                  </figure>
               </div>
               <div class="item overlay overlay-effect">
                  <figure>
                     <a href="team-member.html">
                        <img src="images/team/img2.jpg" alt="" class="img-responsive" />
                     </a>
                     <figcaption>
                        <h3>Mark Anthony</h3>
                        <h5>UI/UX Designer</h5>
                        <ul class="reset-list">
                           <li class="ico-twitter animation">
                              <a href="#">
                                 <span class="icon-twitter"></span>
                              </a>
                           </li>
                           <li class="ico-facebook animation">
                              <a href="#">
                                 <span class="icon-facebook"></span>
                              </a>
                           </li>
                           <li class="ico-pinterest animation">
                              <a href="#">
                                 <span class="icon-pinterest"></span>
                              </a>
                           </li>
                           <li class="ico-instagram animation">
                              <a href="#">
                                 <span class="icon-instagram"></span>
                              </a>
                           </li>
                           <li class="ico-dribbble animation">
                              <a href="#">
                                 <span class="icon-dribbble"></span>
                              </a>
                           </li>
                        </ul>
                     </figcaption>
                  </figure>
               </div>
            </div>
         </div>
      </div>
   </div>
</div><!-- end team carousel -->
<div class="buy hidden">
   <div class="container">
      <div class="row">
         <div class="col-sm-9">
            <h2 class="section-title">This is <span>The Best</span> Multi Purpose Wordpress Theme</h2>
            <h5>It’s Suitable for Corporate, Creative, Personal, Noncommercial Needs</h5>
         </div>
         <div class="col-sm-3 center">
            <a href="#" class="btn btn-default">buy now</a>
         </div>
      </div>
   </div>
</div><!-- end buy section-->