<div class="container mbottom100">
<?php foreach($variable as $item){?>
        <?php
           echo $item->getName();"<br/>"
?>
<?php }?>
   <div class="row">
      <div class="col-sm-4">
         <div class="services-box">
            <span class="icon-images"></span>
            <h3>Việt news</h3>
            <p>Nulla non ms ac is mollis, est non commodo luctus, nisi ula, eget lacinia odio sem nec elit. Aene ndum nulla sed.
               Donec ullamcorper nulla non metus.</p>
            <a href="#">Đọc tiếp</a>
         </div>
      </div>
      <div class="col-sm-4">
         <div class="services-box">
            <span class="icon-lamp3"></span>
            <h3>Học tiếng trung</h3>
            <p>Nulla non ms ac is mollis, est non commodo luctus, nisi ula, eget lacinia odio sem nec elit. Aene ndum nulla sed.
               Donec ullamcorper nulla non metus.</p>
            <a href="#">Đọc tiếp</a>
         </div>
      </div>
      <div class="col-sm-4">
         <div class="services-box">
            <span class="icon-expand"></span>
            <h3>Đài news</h3>
            <p>Nulla non ms ac is mollis, est non commodo luctus, nisi ula, eget lacinia odio sem nec elit. Aene ndum nulla sed.
               Donec ullamcorper nulla non metus.</p>
            <a href="#">Đọc tiếp</a>
         </div>
      </div>
   </div>
</div><!-- end services -->
<div id="featured-projects" class="ptop50 pbottom70 hidden">
   <div class="portfolio-header">
      <div class="container">
         <div class="row">
            <div class="col-sm-6">
               <h2 class="section-title">Featured Projects</h2>
               <h4 class="section-subtitle">It’s Suitable for Corporate, Creative, Personal, Noncommercial Needs</h4>
            </div>
            <div class="col-sm-6">
               <div id="portfolio-filters" class="filters-nav">
                  <ul class="reset-list">
                     <li class="filter-item is-active" data-filter="*">All</li>
                     <li class="filter-item" data-filter=".illustration">Illustration</li>
                     <li class="filter-item" data-filter=".photography">Photography</li>
                     <li class="filter-item" data-filter=".web">Web</li>
                     <li class="filter-item" data-filter=".3d">3D</li>
                  </ul>
               </div>
            </div>
         </div>
      </div>
   </div>
   <div class="portfolio-wrapper">
      <div class="portfolio-item illustration">
         <div class="item-image overlay overlay-effect">
            <figure>
               <a href="single-project.html">
                  <img src="images/projects/img1.jpg" alt="">
               </a>
               <figcaption>
                  <h3>Illustration</h3>
                  <h5>3D Illustration</h5>
                  <span class="icon-heart2">17</span>
               </figcaption>
            </figure>
         </div>
      </div>
      <div class="portfolio-item photography">
         <div class="item-image overlay overlay-effect">
            <figure>
               <a href="single-project.html">
                  <img src="images/projects/img2.jpg" alt="">
               </a>
               <figcaption>
                  <h3>Photography</h3>
                  <h5>Photo, Video</h5>
                  <span class="icon-heart2">5</span>
               </figcaption>
            </figure>
         </div>
      </div>
      <div class="portfolio-item web ">
         <div class="item-image overlay overlay-effect">
            <figure>
               <a href="single-project.html">
                  <img src="images/projects/img3.jpg" alt="">
               </a>
               <figcaption>
                  <h3>Web</h3>
                  <h5>Web Design</h5>
                  <span class="icon-heart2">35</span>
               </figcaption>
            </figure>
         </div>
      </div>
      <div class="portfolio-item 3d">
         <div class="item-image overlay overlay-effect">
            <figure>
               <a href="single-project.html">
                  <img src="images/projects/img4.jpg" alt="">
               </a>
               <figcaption>
                  <h3>3D</h3>
                  <h5>3D Illustration</h5>
                  <span class="icon-heart2">9</span>
               </figcaption>
            </figure>
         </div>
      </div>
      <div class="portfolio-item photography">
         <div class="item-image overlay overlay-effect">
            <figure>
               <a href="single-project.html">
                  <img src="images/projects/img5.jpg" alt="">
               </a>
               <figcaption>
                  <h3>Photography</h3>
                  <h5>3D Illustration</h5>
                  <span class="icon-heart2">20</span>
               </figcaption>
            </figure>
         </div>
      </div>
      <div class="portfolio-item 3d">
         <div class="item-image overlay overlay-effect">
            <figure>
               <a href="single-project.html">
                  <img src="images/projects/img6.jpg" alt="">
               </a>
               <figcaption>
                  <h3>3D</h3>
                  <h5>3D Illustration</h5>
                  <span class="icon-heart2">17</span>
               </figcaption>
            </figure>
         </div>
      </div>
      <div class="portfolio-item web">
         <div class="item-image overlay overlay-effect">
            <figure>
               <a href="single-project.html">
                  <img src="images/projects/img7.jpg" alt="">
               </a>
               <figcaption>
                  <h3>Illustration</h3>
                  <h5>3D Illustration</h5>
                  <span class="icon-heart2">17</span>
               </figcaption>
            </figure>
         </div>
      </div>
      <div class="portfolio-item illustration">
         <div class="item-image overlay overlay-effect">
            <figure>
               <a href="single-project.html">
                  <img src="images/projects/img8.jpg" alt="">
               </a>
               <figcaption>
                  <h3>Illustration</h3>
                  <h5>3D Illustration</h5>
                  <span class="icon-heart2">17</span>
               </figcaption>
            </figure>
         </div>
      </div>
   </div>
</div><!-- end #featured-projects -->
<div class="container ptop50 pbottom70">
   <h2 class="section-title mbottom50">What's New?</h2>
   <div class="row">
      <div class="col-sm-3">
         <div class="news-boxes mbottom35">
            <div class="news-header">
               <span>10</span>
               <span>08</span>
               <h3>Hơn 60 tấn ngao chết trắng biển Hà Tĩnh</h3>
            </div>
            <p class="mbottom30">Donec ullamcorper nulla non ms ac is mollis, est non commodo luctus, nisi ula, eget lacinia odio sem nec elit. Aene ndum nulla sed. Donec ullamcorper nulla non metus ac is mollis, est non commodo luctus.</p>
            <a href="#">More info</a>
         </div>
      </div>
      <div class="col-sm-3">
         <div class="news-boxes mbottom35">
            <div class="news-header">
               <span>10</span>
               <span>07</span>
               <h3>春夏季新款婚纱礼服新娘结婚韩式双肩长拖尾婚纱一字肩</h3>
            </div>
            <p class="mbottom30">Donec ullamcorper nulla non ms ac is mollis, est non commodo luctus, nisi ula, eget lacinia odio sem nec elit. Aene ndum nulla sed. Donec ullamcorper nulla non metus ac is mollis, est non commodo luctus.</p>
            <a href="#">More info</a>
         </div>
      </div>
      <div class="col-sm-3">
         <div class="news-boxes mbottom35">
            <div class="news-header">
               <span>10</span>
               <span>08</span>
               <h3>Hơn 60 tấn ngao chết trắng biển Hà Tĩnh</h3>
            </div>
            <p class="mbottom30">Donec ullamcorper nulla non ms ac is mollis, est non commodo luctus, nisi ula, eget lacinia odio sem nec elit. Aene ndum nulla sed. Donec ullamcorper nulla non metus ac is mollis, est non commodo luctus.</p>
            <a href="#">More info</a>
         </div>
      </div>
      <div class="col-sm-3">
         <div class="news-boxes mbottom35">
            <div class="news-header">
               <span>10</span>
               <span>07</span>
               <h3>春夏季新款婚纱礼服新娘结婚韩式双肩长拖尾婚纱一字肩</h3>
            </div>
            <p class="mbottom30">Donec ullamcorper nulla non ms ac is mollis, est non commodo luctus, nisi ula, eget lacinia odio sem nec elit. Aene ndum nulla sed. Donec ullamcorper nulla non metus ac is mollis, est non commodo luctus.</p>
            <a href="#">More info</a>
         </div>
      </div>
   </div>
</div><!-- end news -->
<div id="team" class="ptop50 pbottom80 hidden">
   <div class="container">
      <div class="row">
         <div class="col-sm-12 relative">
            <h2 class="section-title">Meet Our Team of Best Professionals</h2>
            <div id="our-team">
               <div class="item overlay overlay-effect">
                  <figure>
                     <a href="team-member.html">
                        <img src="images/team/img1.jpg" alt="" class="img-responsive" />
                     </a>
                     <figcaption>
                        <h3>Mark Anthony</h3>
                        <h5>UI/UX Designer</h5>
                        <ul class="reset-list">
                           <li class="ico-twitter animation">
                              <a href="#">
                                 <span class="icon-twitter"></span>
                              </a>
                           </li>
                           <li class="ico-facebook animation">
                              <a href="#">
                                 <span class="icon-facebook"></span>
                              </a>
                           </li>
                           <li class="ico-pinterest animation">
                              <a href="#">
                                 <span class="icon-pinterest"></span>
                              </a>
                           </li>
                           <li class="ico-instagram animation">
                              <a href="#">
                                 <span class="icon-instagram"></span>
                              </a>
                           </li>
                           <li class="ico-dribbble animation">
                              <a href="#">
                                 <span class="icon-dribbble"></span>
                              </a>
                           </li>
                        </ul>
                     </figcaption>
                  </figure>
               </div>
               <div class="item overlay overlay-effect">
                  <figure>
                     <a href="team-member.html">
                        <img src="images/team/img2.jpg" alt="" class="img-responsive" />
                     </a>
                     <figcaption>
                        <h3>Mark Anthony</h3>
                        <h5>UI/UX Designer</h5>
                        <ul class="reset-list">
                           <li class="ico-twitter animation">
                              <a href="#">
                                 <span class="icon-twitter"></span>
                              </a>
                           </li>
                           <li class="ico-facebook animation">
                              <a href="#">
                                 <span class="icon-facebook"></span>
                              </a>
                           </li>
                           <li class="ico-pinterest animation">
                              <a href="#">
                                 <span class="icon-pinterest"></span>
                              </a>
                           </li>
                           <li class="ico-instagram animation">
                              <a href="#">
                                 <span class="icon-instagram"></span>
                              </a>
                           </li>
                           <li class="ico-dribbble animation">
                              <a href="#">
                                 <span class="icon-dribbble"></span>
                              </a>
                           </li>
                        </ul>
                     </figcaption>
                  </figure>
               </div>
               <div class="item overlay overlay-effect">
                  <figure>
                     <a href="team-member.html">
                        <img src="images/team/img3.jpg" alt="" class="img-responsive" />
                     </a>
                     <figcaption>
                        <h3>Mark Anthony</h3>
                        <h5>UI/UX Designer</h5>
                        <ul class="reset-list">
                           <li class="ico-twitter animation">
                              <a href="#">
                                 <span class="icon-twitter"></span>
                              </a>
                           </li>
                           <li class="ico-facebook animation">
                              <a href="#">
                                 <span class="icon-facebook"></span>
                              </a>
                           </li>
                           <li class="ico-pinterest animation">
                              <a href="#">
                                 <span class="icon-pinterest"></span>
                              </a>
                           </li>
                           <li class="ico-instagram animation">
                              <a href="#">
                                 <span class="icon-instagram"></span>
                              </a>
                           </li>
                           <li class="ico-dribbble animation">
                              <a href="#">
                                 <span class="icon-dribbble"></span>
                              </a>
                           </li>
                        </ul>
                     </figcaption>
                  </figure>
               </div>
               <div class="item overlay overlay-effect">
                  <figure>
                     <a href="team-member.html">
                        <img src="images/team/img4.jpg" alt="" class="img-responsive" />
                     </a>
                     <figcaption>
                        <h3>Mark Anthony</h3>
                        <h5>UI/UX Designer</h5>
                        <ul class="reset-list">
                           <li class="ico-twitter animation">
                              <a href="#">
                                 <span class="icon-twitter"></span>
                              </a>
                           </li>
                           <li class="ico-facebook animation">
                              <a href="#">
                                 <span class="icon-facebook"></span>
                              </a>
                           </li>
                           <li class="ico-pinterest animation">
                              <a href="#">
                                 <span class="icon-pinterest"></span>
                              </a>
                           </li>
                           <li class="ico-instagram animation">
                              <a href="#">
                                 <span class="icon-instagram"></span>
                              </a>
                           </li>
                           <li class="ico-dribbble animation">
                              <a href="#">
                                 <span class="icon-dribbble"></span>
                              </a>
                           </li>
                        </ul>
                     </figcaption>
                  </figure>
               </div>
               <div class="item overlay overlay-effect">
                  <figure>
                     <a href="team-member.html">
                        <img src="images/team/img1.jpg" alt="" class="img-responsive" />
                     </a>
                     <figcaption>
                        <h3>Mark Anthony</h3>
                        <h5>UI/UX Designer</h5>
                        <ul class="reset-list">
                           <li class="ico-twitter animation">
                              <a href="#">
                                 <span class="icon-twitter"></span>
                              </a>
                           </li>
                           <li class="ico-facebook animation">
                              <a href="#">
                                 <span class="icon-facebook"></span>
                              </a>
                           </li>
                           <li class="ico-pinterest animation">
                              <a href="#">
                                 <span class="icon-pinterest"></span>
                              </a>
                           </li>
                           <li class="ico-instagram animation">
                              <a href="#">
                                 <span class="icon-instagram"></span>
                              </a>
                           </li>
                           <li class="ico-dribbble animation">
                              <a href="#">
                                 <span class="icon-dribbble"></span>
                              </a>
                           </li>
                        </ul>
                     </figcaption>
                  </figure>
               </div>
               <div class="item overlay overlay-effect">
                  <figure>
                     <a href="team-member.html">
                        <img src="images/team/img2.jpg" alt="" class="img-responsive" />
                     </a>
                     <figcaption>
                        <h3>Mark Anthony</h3>
                        <h5>UI/UX Designer</h5>
                        <ul class="reset-list">
                           <li class="ico-twitter animation">
                              <a href="#">
                                 <span class="icon-twitter"></span>
                              </a>
                           </li>
                           <li class="ico-facebook animation">
                              <a href="#">
                                 <span class="icon-facebook"></span>
                              </a>
                           </li>
                           <li class="ico-pinterest animation">
                              <a href="#">
                                 <span class="icon-pinterest"></span>
                              </a>
                           </li>
                           <li class="ico-instagram animation">
                              <a href="#">
                                 <span class="icon-instagram"></span>
                              </a>
                           </li>
                           <li class="ico-dribbble animation">
                              <a href="#">
                                 <span class="icon-dribbble"></span>
                              </a>
                           </li>
                        </ul>
                     </figcaption>
                  </figure>
               </div>
            </div>
         </div>
      </div>
   </div>
</div><!-- end team carousel -->
<div class="buy hidden">
   <div class="container">
      <div class="row">
         <div class="col-sm-9">
            <h2 class="section-title">This is <span>The Best</span> Multi Purpose Wordpress Theme</h2>
            <h5>It’s Suitable for Corporate, Creative, Personal, Noncommercial Needs</h5>
         </div>
         <div class="col-sm-3 center">
            <a href="#" class="btn btn-default">buy now</a>
         </div>
      </div>
   </div>
</div><!-- end buy section-->