<div class="container mbottom50">
    <div class="row">
        <div class="col-sm-3 sidebar2 mbottom50">
            <h2 class="section-title3 mbottom50">Featured News</h2>
            <ul class="mbottom50 reset-list">
                <li class="clearfix">
                    <a href="blog-post.html">
                        <img src="images/blog/small1.jpg" alt="" />
                    </a>
                    <a href="#"><h4>Fusce dapibus, tellus ac cursus</h4></a>
                    <span class="tag">design, illustration</span>
                    <span class="icon-heart2 mleft10"><b>17</b></span>
                    <span class="icon-bubbles4 mleft10"><b class="mleft5">28</b></span>
                </li>
                <li class="clearfix">
                    <a href="blog-post.html">
                        <img src="images/blog/small2.jpg" alt="" />
                    </a>
                    <a href="#"><h4>Lorem ipsum dolor sit amet, consectetur</h4></a>
                    <span class="tag">people, marketing</span>
                    <span class="icon-heart2 mleft10"><b>11</b></span>
                    <span class="icon-bubbles4 mleft10"><b class="mleft5">18</b></span>
                </li>
                <li class="clearfix">
                    <a href="blog-post.html">
                        <img src="images/blog/small3.jpg" alt="" />
                    </a>
                    <a href="#"><h4>Voluptatem sequi nesciun</h4></a>
                    <span class="tag">design, illustration</span>
                    <span class="icon-heart2 mleft10"><b>19</b></span>
                    <span class="icon-bubbles4 mleft10"><b class="mleft5">35</b></span>
                </li>
                <li class="clearfix">
                    <a href="blog-post.html">
                        <img src="images/blog/small4.jpg" alt="" />
                    </a>
                    <a href="#"><h4>Fusce dapibus, tellus ac cursus</h4></a>
                    <span class="tag">people, marketing</span>
                    <span class="icon-heart2 mleft10"><b>21</b></span>
                    <span class="icon-bubbles4 mleft10"><b class="mleft5">25</b></span>
                </li>
                <li class="clearfix">
                    <a href="blog-post.html">
                        <img src="images/blog/small5.jpg" alt="" />
                    </a>
                    <a href="#"><h4>Voluptatem sequi nesciunt</h4></a>
                    <span class="tag">tips</span>
                    <span class="icon-heart2 mleft10"><b>10</b></span>
                    <span class="icon-bubbles4 mleft10"><b class="mleft5">41</b></span>
                </li>
            </ul>
            <h2 class="section-title3 mbottom30">Twitter Feed</h2>
            <ul class="twitter-feed reset-list">
                <li class="clearfix">
                    <span class="icon-twitter"></span>
                    <h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</h3>
                    <span class="date">3 days ago</span>
                </li>
                <li class="clearfix">
                    <span class="icon-twitter"></span>
                    <h3>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.</h3>
                    <span class="date">4 days ago</span>
                </li>
            </ul>
        </div><!-- end sidebar2 -->
        <div class="col-sm-6 mbottom50">
            <h2 class="section-title3 mbottom50">Web Design</h2>
            <div class="blog-post mbottom50">
                <a href="blog-post.html">
                    <img src="images/blog/img1.jpg" alt="" class="img-responsive mbottom30" />
                </a>
                <div class="post-head mbottom30">
                    <h2>Aliquam accumsan mattis diam, eu dapibus purus tristique convallis. Donec arcu nisi, iaculis a feugiat vitae, mollis non urna. Vestibulum erat diams.</h2>
                    <span class="tcolor">June 22, 2013</span>
                    <span class="icon-heart2 mleft10"><b>17</b></span>
                    <span class="icon-bubbles4 mleft10 mright10"><b class="mleft5">28</b></span>
                    <span class="italic">people, marketing</span>
                </div>
                <div class="post-content">
                    <p class="mbottom20">Aliquam accumsan mattis diam, eu dapibus purus tristique convallis. Donec arcu nisi, iaculis a feugiat vitae, mollis non urna. Vestibulum erat diam, pretium non commodo eu.</p>
                    <a href="#">More info</a>
                </div>
            </div>
            <div class="blog-post mbottom50">
                <iframe class="blog-video mbottom30" src="//player.vimeo.com/video/62158541?title=0&amp;byline=0&amp;portrait=0"></iframe>
                <div class="post-head mbottom30">
                    <h2>Aliquam accumsan mattis diam, eu dapibus purus tristique convallis. Donec arcu nisi, iaculis a feugiat vitae, mollis non urna. Vestibulum erat diams.</h2>
                    <span class="tcolor">June 22, 2013</span>
                    <span class="icon-heart2 mleft10"><b>17</b></span>
                    <span class="icon-bubbles4 mleft10 mright10"><b class="mleft5">28</b></span>
                    <span class="italic">people, marketing</span>
                </div>
                <div class="post-content">
                    <p class="mbottom20">Aliquam accumsan mattis diam, eu dapibus purus tristique convallis. Donec arcu nisi, iaculis a feugiat vitae, mollis non urna. Vestibulum erat diam, pretium non commodo eu.</p>
                    <a href="#">More info</a>
                </div>
            </div>
            <div class="blog-post mbottom50">
                <div class="blog-carousel owl-carousel owl-theme mbottom30">
                    <div class="item">
                        <img src="images/blog/img2.jpg" alt="" class="img-responsive" />
                    </div>
                    <div class="item">
                        <img src="images/blog/img3.jpg" alt="" class="img-responsive" />
                    </div>
                    <div class="item">
                        <img src="images/blog/img4.jpg" alt="" class="img-responsive" />
                    </div>
                </div>
                <div class="post-head mbottom30">
                    <h2>Aliquam accumsan mattis diam, eu dapibus purus tristique convallis. Donec arcu nisi, iaculis a feugiat vitae, mollis non urna. Vestibulum erat diams.</h2>
                    <span class="tcolor">June 22, 2013</span>
                    <span class="icon-heart2 mleft10"><b>17</b></span>
                    <span class="icon-bubbles4 mleft10 mright10"><b class="mleft5">28</b></span>
                    <span class="italic">people, marketing</span>
                </div>
                <div class="post-content">
                    <p class="mbottom20">Aliquam accumsan mattis diam, eu dapibus purus tristique convallis. Donec arcu nisi, iaculis a feugiat vitae, mollis non urna. Vestibulum erat diam, pretium non commodo eu.</p>
                    <a href="#">More info</a>
                </div>
            </div>
            <div class="blog-post mbottom50">
                <div class="testimonials5 owl-carousel owl-theme mbottom30">
                    <div class="item">
                        <blockquote>I believe in Karma. If the good is sown, the good is collected. When positive things are made, that returns well."</blockquote>
                        <h5 class="white">- Yannick Noah</h5>
                    </div>
                    <div class="item">
                        <blockquote>I always like to look on the optimistic side of life, but I am realistic enough to know that life is a complex matter."</blockquote>
                        <h5 class="white">- Shahnaz Yana</h5>
                    </div>
                    <div class="item">
                        <blockquote>Work hard, stay positive, and get up early. It's the best part of the day."</blockquote>
                        <h5 class="white">- Maria Blanche</h5>
                    </div>
                </div>
                <div class="post-head mbottom30">
                    <span class="tcolor">June 22, 2013</span>
                    <span class="icon-heart2 mleft10"><b>17</b></span>
                    <span class="icon-bubbles4 mleft10 mright10"><b class="mleft5">28</b></span>
                    <span class="italic">people, marketing</span>
                </div>
            </div>
            <div class="center">
                <ul class="pagination clearfix reset-list">
                    <li><a href="#">&laquo;</a></li>
                    <li class="active"><a href="#">1</a></li>
                    <li><a href="#">2</a></li>
                    <li><a href="#">3</a></li>
                    <li><a href="#">4</a></li>
                    <li><a href="#">5</a></li>
                    <li><a href="#">&raquo;</a></li>
                </ul>
            </div><!-- end pagination -->
        </div>
        <?php $this->widget('app.Widget.Categorys'); ?>
    </div>
</div>