<?php
$document = $this->document();
/** lấy ra danh mục(category của website) */
$categoryAll = \Category::select()->execute();
/* @var BackendBase $controller */

?>

<div class="col-sm-3">
    <div class="sidebar mbottom50">
        <div class="advertisment mbottom50">
            <p>Hiển thị fanpage facebook ở đây</p>
            <img src="template_madarin/images/advertisment.jpg" alt="" class="img-responsive" />
        </div>
        <div class="widget-categories mbottom50">
            <h3>Danh mục</h3>
            <ul class="reset-list">
                <?php foreach ($categoryAll as $category){ ?>
                    <?php /** @var $category \Category */ ?>
                <li>
                    <a href="<?= $controller->createUrl('tin-tuc',['code'=> $category->getId()])  ?>"><?php echo $category->getCategoryName();?></a>

                </li>
                <?php } ?>
            </ul>
        </div>
        <div class="widget-tags mbottom50">
            <h3>Tags</h3>
            <ul class="reset-list">
                <li>
                    <a href="#">design</a>
                </li>
                <li>
                    <a href="#">development</a>
                </li>
                <li>
                    <a href="#">marketing</a>
                </li>
                <li>
                    <a href="#">project</a>
                </li>
                <li>
                    <a href="#">inspiration</a>
                </li>
                <li>
                    <a href="#">tutorials</a>
                </li>
                <li>
                    <a href="#">interviews</a>
                </li>
                <li>
                    <a href="#">web</a>
                </li>
                <li>
                    <a href="#">wordpress</a>
                </li>
                <li>
                    <a href="#">links</a>
                </li>
                <li>
                    <a href="#">resources</a>
                </li>
            </ul>
        </div>
        <div class="advertisment2">
            <p>Advertisment</p>
            <img src="template_madarin/images/advertisment2.jpg" alt="" class="img-responsive" />
            <img src="template_madarin/images/advertisment2.jpg" alt="" class="img-responsive" />
            <img src="template_madarin/images/advertisment2.jpg" alt="" class="img-responsive" />
            <img src="template_madarin/images/advertisment2.jpg" alt="" class="img-responsive" />
            <div class="clearfix"></div>
        </div>
    </div><!-- end sidebar -->
    <?php
        $query = News::select();
        $query->orderBy('id', 'DESC');
        $query->setFirstResult(0)->setMaxResults(5);
        $news = $query->execute();
    ?>
    <div class="sidebar2 mbottom50">
        <h2 class="section-title3 mbottom30">Tin mới</h2>
        <ul class="mbottom50 reset-list">
            <?php foreach ($news as $item){ ?>
                <?php /** @var $item \News */ ?>
            <li class="clearfix">
                <img src="<?php echo $item->getImage() ?>" alt="" />
                <a href="<?= $controller->createUrl('chi-tiet-bai-viet',['code'=> $item->getId()])  ?>"><h4><?php echo $item->getTitle()?></h4></a>
                <span class="tag">design, illustration</span>
                <span class="icon-heart2 mleft10"><b>17</b></span>
                <span class="icon-bubbles4 mleft10"><b class="mleft5">28</b></span>
            </li>
            <?php  } ?>
        </ul>
    </div><!-- end sidebar2 -->
</div>