<footer class="footer-style2">
    <div class="container">
        <div class="row">
            <div class="col-sm-3 mbottom30">
                <a href="index.html">
                    <img src="template_madarin/images/footer-logo.png" alt="" class="default" />
                    <img src="template_madarin/images/footer-logo2.png" alt="" class="only3" />
                </a>
                <p class="mtop30">Etiam accumsan tristique diam, nec mollis nulla. Interdum et malesuada fames ac ante ipsum primis in faucibus.</p>
                <div class="social mtop25 mbottom30 clearfix">
                    <ul class="reset-list">
                        <li class="ico-twitter animation">
                            <a href="#">
                                <span class="icon-twitter"></span>
                            </a>
                        </li>
                        <li class="ico-facebook animation">
                            <a href="#">
                                <span class="icon-facebook"></span>
                            </a>
                        </li>
                        <li class="ico-google animation">
                            <a href="#">
                                <span class="icon-googleplus"></span>
                            </a>
                        </li>
                        <li class="ico-pinterest animation">
                            <a href="#">
                                <span class="icon-pinterest"></span>
                            </a>
                        </li>
                        <li class="ico-dribbble animation">
                            <a href="#">
                                <span class="icon-dribbble"></span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-sm-3 mbottom30">
                <h3>Blogger</h3>
                <ul class="footer-blog reset-list">
                    <li>
                        <a href="blog-post.html">
                            <img src="template_madarin/images/footer-img.jpg" alt=""/>
                        </a>
                        <p>Cảm nhận về văn hóa Việt</p>
                        <p class="tcolor">June 22, 2013</p>
                        <div class="clearfix mbottom20"></div>
                    </li>
                    <li>
                        <a href="blog-post.html">
                            <img src="template_madarin/images/footer-img2.jpg" alt=""/>
                        </a>
                        <p>Cảm nhận về văn hóa Đài Loan</p>
                        <p class="tcolor">June 22, 2013</p>
                        <div class="clearfix"></div>
                    </li>
                </ul>
            </div>
            <div class="col-sm-3 mbottom30">
                <h3>MADARIN</h3>
                <ul class="menu-list reset-list">
                    <li>
                        <a href="#">Chúng tôi</a>
                    </li>
                    <li>
                        <a href="contact.html">Liên hệ</a>
                    </li>
                    <li>
                        <a href="#">Chính sách</a>
                    </li>
                    <li>
                        <a href="#">Mục tiêu</a>
                    </li>
                    <!--<li>
                        <a href="testimonials.html">Testimonials</a>
                    </li>-->
                </ul>
            </div>
            <div class="col-sm-3">
                <h3>Gửi phản hồi</h3>
                <div id="subscribe" class="footer-subscribe center mbottom10">
                    <form action="http://lorthemes.us8.list-manage1.com/subscribe/post-json?u=42795504a248e486766e563b9&amp;id=f766078320&amp;c=?" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="validate" target="_blank" novalidate>
                        <input type="email" value="" name="EMAIL" class="email" id="mce-EMAIL" placeholder="" required>
                        <div style="position: absolute; left: -5000px;">
                            <input type="text" name="b_9ed253451c5b914e9c34e388b_6e3ba686ba" value="">
                        </div>
                        <button class=" btn-sm btn-small" type="submit" name="subscribe" id="mc-embedded-subscribe"><span class="icon-envelope"></span></button>
                    </form>
                    <div id="notification_container"></div>
                </div>
                <p>By subscribing to our mailing list you will always be update with the latest news from us.</p>
            </div>
        </div>
    </div>
    <div class="bottom-footer">
        <div class="container">
            <div class="row ptop10">
                <div class="col-sm-6 col-xs-12 mbottom20">
                    <p class="copyright">© 2014 - 2015 developed by <strong>Nguyễn Hoàng Giang</strong>. All Rights Reserved</p>
                </div>
                <div class="col-sm-6 col-xs-12">
                    <div class="social-buttons">
                        <div class="facebook-button">
                            <!-- Change this iframe with your own. -->
                            <iframe src="//www.facebook.com/plugins/like.php?href=https%3A%2F%2Fwww.facebook.com%2FEnvatoStudio&amp;width&amp;layout=button_count&amp;action=like&amp;show_faces=false&amp;share=false&amp;height=21" scrolling="no" frameborder="0" style="border:none; overflow:hidden; height:21px;" allowTransparency="true"></iframe>
                        </div>
                        <div class="twitter-button">
                            <!-- Change data-via to your own. -->
                            <a href="https://twitter.com/share" class="twitter-share-button" data-via="BogdanStw">Tweet</a>
                            <script>
                                !function(d,s,id){
                                    var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';
                                    if(!d.getElementById(id)){
                                        js=d.createElement(s);
                                        js.id=id;
                                        js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');
                            </script>
                        </div>
                        <div class="google-button">
                            <!-- Place this tag where you want the +1 button to render. -->
                            <div class="g-plusone" data-size="medium"></div>
                            <!-- Place this tag after the last +1 button tag. -->
                            <script type="text/javascript">
                                (function() {
                                        var po = document.createElement('script');
                                        po.type = 'text/javascript';
                                        po.async = true;
                                        po.src = 'https://apis.google.com/js/plusone.js';
                                        var s = document.getElementsByTagName('script')[0];
                                        s.parentNode.insertBefore(po, s);
                                    }
                                )();
                            </script>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</footer>