<?php
$query = \Menus::select();
$menus = $query->execute();

$name_menu= [];
foreach ($menus as $item_menu){
    /** @var $item_menu \Menus */
    $name_menu[] = $item_menu;
}

?>

<header id="header" class="nav-down header3">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="relative onlyh3">
                    <div class="logo-container hasinfocard">
                        <h1 id="logo">
                            <a href="javascript:">
                                <img src="template_madarin/images/favicons/logo.png" width="41px" height="184px" alt="CleanLab HTML Template" title="Click to return to CleanLab Template's homepage" class="img-responsive non-transparent">
                            </a>
                        </h1><!-- end logo -->
                    </div><!-- end logo-container -->

                    <div class="searchPanel">
                        <span class="icon-search3"></span>
                        <form action="http://www.google.com/search" method="get" onsubmit="Gsitesearch(this)" target="_blank" class="searchForm">
                            <input name="qfront" type="text" placeholder="just type in here..." class="searchBox">
                        </form>
                    </div><!-- end searchPanel -->
                    <div class="dropdown language">
                        <span class=""></span>
                        <div class="dropdown">
							<span class="globe icon-earth" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
							</span>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                                <li role="presentation">
                                    <a role="menuitem" tabindex="-1" href="#">English</a>
                                    <img src="template_madarin/images/flags/us.png" alt="English" class="flag-img">
                                </li>
                                <li role="presentation">
                                    <a role="menuitem" tabindex="-1" href="#">Spanish</a>
                                    <img src="template_madarin/images/flags/es.png" alt="Việt nam" class="flag-img">
                                </li>
                                <li role="presentation">
                                    <a role="menuitem" tabindex="-1" href="#">French</a>
                                    <img src="template_madarin/images/flags/fr.png" alt="Đài loan" class="flag-img">
                                </li>
                            </ul>
                        </div>
                    </div><!-- end language -->
                    <!-- Responsive Menu -->
                    <div class="zn-res-menuwrapper">
                        <a class="zn-res-trigger" href="#"></a>
                    </div>
                    <div id="main-menu">
                        <ul>
                            <?php foreach ($name_menu as $item){ ?>
                                <li class="has-sub">
                                    <?php /** @var $item \Menus */ ?>
                                    <a href="<?=$item->getAlias() ?>"><?=$item->getName()?></a>
                                </li>
                            <?php } ?>
                            <!--<li class="has-sub active">
                                <a href="#">Trang chủ</a>
                            </li>
                            <li class="has-sub mega">
                                <a href="index.html">Học Tiếng Trung</a>
                                <ul class="mega-menu container clearfix">
                                    <li class="col-sm-3">
                                        <a href="http://#" class="mega-title">Homepages examples 1</a>
                                        <ul class="sub-menu clearfix">
                                            <li>
                                                <a href="home-layout-1.html">Home Layout 1</a>
                                            </li>
                                            <li>
                                                <a href="home-layout-2.html">Home Layout 2</a>
                                            </li>
                                            <li>
                                                <a href="home-layout-3.html">Home Layout 3</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="col-sm-3">
                                        <a href="http://#" class="mega-title">Homepages examples 2</a>
                                        <ul class="sub-menu clearfix">
                                            <li>
                                                <a href="home-layout-4.html">Home Layout 4</a>
                                            </li>
                                            <li>
                                                <a href="home-layout-5.html">Home Layout 5</a>
                                            </li>
                                            <li>
                                                <a href="home-layout-6.html">Home Layout 6</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="col-sm-3">
                                        <a href="http://#" class="mega-title">Homepages examples 3</a>
                                        <ul class="sub-menu clearfix">
                                            <li>
                                                <a href="home-layout-7.html">Home Layout 7</a>
                                            </li>
                                            <li>
                                                <a href="home-layout-8.html">Home Layout 8</a>
                                            </li>
                                            <li>
                                                <a href="home-layout-9.html">Home Layout 9</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="col-sm-3">
                                        <a href="http://#" class="mega-title">Homepages examples 4</a>
                                        <ul class="sub-menu clearfix">
                                            <li>
                                                <a href="home-layout-10.html">Home Layout 10</a>
                                            </li>
                                            <li>
                                                <a href="one-page.html">One Page</a>
                                            </li>
                                            <li>
                                                <a href="full-page.html">Full Page</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>

                            <li class="has-sub">
                                <a href="#">VIỆT NEWS</a>
                                <ul>
                                    <li>
                                        <a href="portfolio.html">Portfolio</a>
                                    </li>
                                    <li>
                                        <a href="portfolio-simple.html">Portfolio Simple Layout</a>
                                    </li>
                                    <li>
                                        <a href="portfolio-full-width.html">Portfolio - Full Width</a>
                                    </li>
                                    <li>
                                        <a href="single-project.html">Single Project</a>
                                    </li>
                                </ul>
                            </li>
                            <li>
                                <a href="#">ĐÀI LOAN NEWS</a>
                                <ul>
                                    <li>
                                        <a href="blog.html">Blog Style 1</a>
                                    </li>
                                    <li>
                                        <a href="blog-2.html">Blog Style 2</a>
                                    </li>
                                    <li>
                                        <a href="blog-3.html">Blog Style 3</a>
                                    </li>
                                    <li>
                                        <a href="blog-4.html">Blog Style 4</a>
                                    </li>
                                    <li>
                                        <a href="blog-timeline.html">Timeline Blog</a>
                                    </li>
                                    <li>
                                        <a href="blog-masonry.html">Masonry Blog</a>
                                    </li>
                                    <li>
                                        <a href="blog-masonry-full.html">Masonry Blog Full</a>
                                    </li>
                                    <li>
                                        <a href="blog-post.html">Blog Post Style 1</a>
                                    </li>
                                    <li>
                                        <a href="blog-post-2.html">Blog Post Style 2</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="has-sub mega">
                                <a href="contact.html">LIÊN HỆ</a>
                                <ul class="mega-menu container clearfix hidden">
                                    <li class="col-sm-3">
                                        <a href="http://#" class="mega-title">Pages examples 1</a>
                                        <ul class="sub-menu clearfix">
                                            <li>
                                                <a href="full-width-page.html">Full Width</a>
                                            </li>
                                            <li>
                                                <a href="left-sidebar-page.html">Left Sidebar</a>
                                            </li>
                                            <li>
                                                <a href="right-sidebar-page.html">Right Sidebar</a>
                                            </li>
                                            <li>
                                                <a href="text-page.html">Text Page</a>
                                            </li>
                                            <li>
                                                <a href="product-launch.html">Product Launch</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="col-sm-3">
                                        <a href="http://#" class="mega-title">Pages examples 2</a>
                                        <ul class="sub-menu clearfix">
                                            <li>
                                                <a href="faq.html">FAQ</a>
                                            </li>
                                            <li>
                                                <a href="testimonials.html">Testimonials</a>
                                            </li>
                                            <li>
                                                <a href="features.html">Features</a>
                                            </li>
                                            <li>
                                                <a href="our-office.html">Our Office</a>
                                            </li>
                                            <li>
                                                <a href="pricing.html">Pricing</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="col-sm-3">
                                        <a href="http://#" class="mega-title">Pages examples 3</a>
                                        <ul class="sub-menu clearfix">
                                            <li>
                                                <a href="timeline-page.html">Timeline Page</a>
                                            </li>
                                            <li>
                                                <a href="clients.html">Clients</a>
                                            </li>
                                            <li>
                                                <a href="team.html">Our Team</a>
                                            </li>
                                            <li>
                                                <a href="team-member.html">Team Member</a>
                                            </li>
                                            <li>
                                                <a href="about-us.html">About us</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="col-sm-3">
                                        <a href="http://#" class="mega-title">Pages examples 4</a>
                                        <ul class="sub-menu clearfix">
                                            <li>
                                                <a href="coming-soon.html">Coming Soon</a>
                                            </li>
                                            <li>
                                                <a href="maintenance-mode.html">Maintenance Mode</a>
                                            </li>
                                            <li>
                                                <a href="contact.html">Contact Page</a>
                                            </li>
                                            <li>
                                                <a href="sitemap.html">Sitemap</a>
                                            </li>
                                            <li>
                                                <a href="404.html">404 Error Page</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>-->
                        </ul>
                    </div><!-- end main menu -->
                </div>
            </div>
        </div>
    </div>
</header>