<?php
$query = \Menus::select();
$menus = $query->execute();

$name_menu= [];
foreach ($menus as $item_menu){
    /** @var $item_menu \Menus */
    $name_menu[] = $item_menu->toArray();
}

?>

<header id="header" class="nav-down header3">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="relative onlyh3">
                    <div class="logo-container hasinfocard">
                        <h1 id="logo">
                            <a href="javascript:">
                                <img src="template_madarin/images/favicons/logoweb.png" width="45px" height="50px" alt="CleanLab HTML Template" title="Click to return to CleanLab Template's homepage" class="img-responsive non-transparent">
                            </a>
                        </h1><!-- end logo -->
                    </div><!-- end logo-container -->

                    <div class="searchPanel">
                        <span class="icon-search3"></span>
                        <form action="http://www.google.com/search" method="get" onsubmit="Gsitesearch(this)" target="_blank" class="searchForm">
                            <input name="qfront" type="text" placeholder="just type in here..." class="searchBox">
                        </form>
                    </div><!-- end searchPanel -->
                    <div class="dropdown language">
                        <span class=""></span>
                        <div class="dropdown">
							<span class="globe icon-earth" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-expanded="true">
							</span>
                            <ul class="dropdown-menu" role="menu" aria-labelledby="dropdownMenu1">
                                <li role="presentation">
                                    <a role="menuitem" tabindex="-1" href="#">English</a>
                                    <img src="template_madarin/images/flags/us.png" alt="English" class="flag-img">
                                </li>
                                <li role="presentation">
                                    <a role="menuitem" tabindex="-1" href="#">Spanish</a>
                                    <img src="template_madarin/images/flags/es.png" alt="Việt nam" class="flag-img">
                                </li>
                                <li role="presentation">
                                    <a role="menuitem" tabindex="-1" href="#">French</a>
                                    <img src="template_madarin/images/flags/fr.png" alt="Đài loan" class="flag-img">
                                </li>
                            </ul>
                        </div>
                    </div><!-- end language -->
                    <!-- Responsive Menu -->
                    <div class="zn-res-menuwrapper">
                        <a class="zn-res-trigger" href="#"></a>
                    </div>
                    <div id="main-menu">
<!--                       --><?php
//                            function showMenu($menu,$parent_id = 0, $char = ''){
//                                foreach ($menu as $key => $item_menu){
//                                    if($item_menu['parent'] == $parent_id){
//                                        echo '<option value="'.$item_menu[$key].'">';
//                                            echo $char.$item_menu['name'];
//                                        echo '<option>';
//                                        unset($menu[$key]);
//                                        showMenu($menu, $item_menu['id'], $char.'|---');
//                                    }
//                                }
//                            }
//                       ?>
<!---->
<!--                        <select>-->
<!--                            --><?php //showMenu($name_menu); ?>
<!--                        </select>-->


                        <ul>
                            <li class="has-sub mega">
                                <a href="index.html">HOME</a>
                            </li>
                            <li class="has-sub active">
                                <a href="#">News</a>
                                <ul>
                                    <li>
                                        <a href="full-screen.html">Taiwan news</a>
                                    </li>
                                    <li>
                                        <a href="boxed-slideshow.html">Vietnam News</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="has-sub">
                                <a href="#">Learn VietNamese</a>
                            </li>
                            <li class="has-sub mega">
                                <a href="index.html">Learn Taiwan</a>
                                <ul class="mega-menu container clearfix" style="width: 600px;!important;margin: 0px;!important;">
                                    <li class="col-sm-6">
                                        <a href="http://#" class="mega-title">Khóa học cơ bản</a>
                                        <ul class="sub-menu clearfix">
                                            <li>
                                                <a href="home-layout-1.html">Home Layout 1</a>
                                            </li>
                                            <li>
                                                <a href="home-layout-2.html">Home Layout 2</a>
                                            </li>
                                            <li>
                                                <a href="home-layout-3.html">Home Layout 3</a>
                                            </li>
                                        </ul>
                                    </li>
                                    <li class="col-sm-6">
                                        <a href="http://#" class="mega-title">Ôn thi</a>
                                        <ul class="sub-menu clearfix">
                                            <li>
                                                <a href="home-layout-4.html">Home Layout 4</a>
                                            </li>
                                            <li>
                                                <a href="home-layout-5.html">Home Layout 5</a>
                                            </li>
                                            <li>
                                                <a href="home-layout-6.html">Home Layout 6</a>
                                            </li>
                                        </ul>
                                    </li>
                                </ul>
                            </li>
                            <li class="has-sub mega">
                                <a href="#">BLOGGER</a>
                            </li>
                            <li class="has-sub">
                                <a href="#">LIÊN HỆ</a>
                            </li>
                        </ul>
                    </div><!-- end main menu -->
                </div>
            </div>
        </div>
    </div><!-- end main menu -->



</header>